# -*- coding: utf-8 -*-
"""Copia de Copia de Procesado TFM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkKAnTFgvcvpzPYvPVRrVCSuBSROrKFq

**TRABAJO DE FIN DE MÁSTER (TFM)**


**ANEXO METODOLÓGICO: PIPELINE BIOINFORMÁTICO (MODELO V31)**
Este script centraliza el post-procesado de los archivos de antiSMASH, la
reducción de redundancia mediante CD-HIT, la auditoría de secuencias, la
transformación algebraica TF-IDF y el entramado predictivo de Machine Learning
(Isolation Forest, XGBoost y SHAP).

Se ha estructurado para ejecutarse de forma secuencial garantizando la
reproducibilidad de los resultados presentados en la memoria.

📂** Estructura del Repositorio y Correspondencia con la Memoria**
El código se ha dividido lógicamente en los siguientes módulos, correspondientes a los Anexos detallados en el apartado de Materiales y Métodos (3.4.3 y 3.5):

01_extraccion_antismash.py (Anexo 3.7.1 - Post-procesado de antiSMASH)

02_clustering_y_hmmer.py (Anexo 3.7.1 - CD-HIT y API EBI)

03_matriz_tfidf.py (Anexo 3.7.2 - Construcción matricial)

04_modelo_v31_xgboost.py (Anexo 3.7.4 - Machine Learning y SHAP)

**Módulo 1: Extracción, Tipado Automatizado y Minería Funcional de Clústeres Biosintéticos (BGCs)**

Este módulo inicial gestiona la ingesta masiva de datos genómicos y la extracción sistemática de los Clústeres de Genes Biosintéticos (BGCs) a partir de los outputs crudos generados por antiSMASH.

Procesamiento e Ingesta: Automatiza la descompresión de archivos genómicos (.zip) estructurados por aislamiento/cepa fúngica y el parseo de registros secuenciales en formato GenBank (.gbk).

Corrección de Clústeres Híbridos: Implementa un control de calidad que detecta y corrige anomalías sintácticas en la clasificación de productos biosintéticos híbridos (p. ej., fusiones NRPS-PKS), reestructurando su nomenclatura para evitar sesgos numéricos posteriores en las matrices pangenómicas.

Clasificación Ontológica Estricta: Evalúa la ontología génica de cada locus mediante un filtro heurístico riguroso basado en palabras clave específicas y perfiles Pfam. Segmenta los elementos de la región en cinco categorías funcionales discretas: Core (genes biosintéticos clave), Accessory (enzimas adicionales de modificación), Transporter (bombas de eflujo y permeasas ABC/MFS), Regulator (factores de transcripción y proteínas de unión a ADN) y Other.

Anotación Remota por HMMER/Pfam: En caso de que un gen biosintético carezca de dominios preestablecidos, el pipeline integra consultas asíncronas a la API REST de HMMER (EBI) mediante el servicio hmmscan contra la base de datos Pfam, blindando la completitud de la caracterización funcional.

Minería de Similitud MIBiG: Ejecuta una minería directa sobre los archivos de alineamiento knownclusterblast.txt para extraer de forma inequívoca el identificador del BGC homólogo en el repositorio MIBiG junto con su porcentaje exacto de identidad evolutiva.
"""

# =====================================================================
# INSTALACIÓN DE DEPENDENCIAS Y SOFTWARE EXTERNO
# =====================================================================

# 1. Librerías de Python (Secuencias, Gráficos, Clinker y Excel)
!pip install biopython upsetplot dna_features_viewer clinker openpyxl

# 2. Software de línea de comandos (CD-HIT para clustering)
!apt-get update
!apt-get install -y cd-hit
# 3. Para machine learning
!pip install xgboost shap scikit-learn biopython openpyxl

import os
import glob
import zipfile
import shutil
import re
import warnings
import subprocess
import pandas as pd
import matplotlib.pyplot as plt
import requests
import time
from typing import Tuple
from Bio import SeqIO, BiopythonWarning
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq

# Dependencias opcionales para gráficas
try:
    from upsetplot import plot as upset_plot
    USE_UPSET = True
except ImportError:
    USE_UPSET = False

try:
    from dna_features_viewer import GraphicFeature, GraphicRecord
    USE_DFV = True
except ImportError:
    USE_DFV = False

# =====================================================================
# Configuración inicial y rutas
# =====================================================================
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=BiopythonWarning)
pd.set_option('future.no_silent_downcasting', True)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

PATH_DRIVE = '/content/drive/MyDrive/TFM/antismash'
PATH_WORK = '/content/datos_botrytis'
PATH_CLINKER = '/content/agrupaciones_clinker'
PATH_RESULTS = os.path.join(PATH_DRIVE, "Resultados_Pangenomicos_Final")

for d in [PATH_WORK, PATH_CLINKER, PATH_RESULTS]:
    os.makedirs(d, exist_ok=True)

# =====================================================================
# Funciones auxiliares (HMMER, MIBiG, Ontología, Gráficos)
# =====================================================================
def buscar_pfam_online(secuencia: str) -> str:
    """Consulta la API de HMMER (EBI) mediante secuencia FASTA."""
    if not secuencia or len(secuencia) < 15:
        return "Invalid_Sequence"

    url = 'https://www.ebi.ac.uk/Tools/hmmer/search/hmmscan'
    headers = {'Accept': 'application/json'}

    data = {
        'hmmdb': 'pfam',
        'seq': f">query_sequence\n{secuencia}"
    }

    try:
        time.sleep(1.5) # Evitar saturar la API
        response = requests.post(url, headers=headers, data=data, timeout=45)

        if response.status_code == 200:
            json_data = response.json()
            pfams = set()
            hits = json_data.get('results', {}).get('hits', [])
            for hit in hits:
                acc = hit.get('acc', '')
                if acc.startswith('PF'):
                    pfams.add(acc.split('.')[0])

            return " | ".join(sorted(list(pfams))) if pfams else "No_Pfam_Hits"
        else:
            print(f"  [!] Error en API HMMER: {response.status_code}")
            return "Not_Annotatable_Online"

    except Exception:
        return "Network_Timeout"

def minar_raw_mibig(gbk_path: str) -> Tuple[str, int]:
    """Extrae el hit de MIBiG y la similitud del archivo txt generado por antiSMASH."""
    dir_base = os.path.dirname(gbk_path)
    txt_files = glob.glob(os.path.join(dir_base, "**", "*knownclusterblast*.txt"), recursive=True)

    for txt_path in txt_files:
        try:
            with open(txt_path, 'r') as f:
                for line in f:
                    if "BGC0" in line:
                        data = line.strip().split('\t')
                        bgc_id = next((x for x in data if x.startswith("BGC")), "Orphan")
                        nums = re.findall(r'\d+', line)
                        sim = int(nums[-1]) if nums else 0
                        return bgc_id, sim
        except Exception: continue
    return "Orphan", 0

def clasificar_gen_ontologia_estricta(gen_txt: str, gene_kind: str) -> str:
    """Clasifica la función del gen basándose en keywords y pfams."""
    gen_txt_lower = gen_txt.lower()

    is_core_domain = any(k in gen_txt_lower for k in [
        'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
        'terpene synthase', 'terpene cyclase', 'phytoene synthase', 'prenyltransferase',
        'sesquiterpene', 'diterpene', 'cyclase'
    ])
    if gene_kind == 'biosynthetic' or is_core_domain: return 'Core'
    if any(k in gen_txt_lower for k in ['transport', 'efflux', 'permease', 'pump', 'abc', 'mfs', 'pf00083', 'pf07690', 'pf00664']): return 'Transporter'
    if any(k in gen_txt_lower for k in ['regulat', 'transcription', 'binding', 'pf00196', 'pf04083', 'pf00228']): return 'Regulator'

    accesorios_keywords = ['p450', 'cytochrome', 'pf00067', 'dehydrogenase', 'reductase', 'oxidase', 'methyltransferase', 'halogenase', 'mutase', 'isomerase']
    if gene_kind == 'biosynthetic-additional' or any(k in gen_txt_lower for k in accesorios_keywords): return 'Accessory'
    return 'Other'

def dibujar_singleton_funcional(gbk_path: str, output_svg: str):
    """Mapeo del cluster lineal coloreado por función (SVG)."""
    if not USE_DFV: return
    try:
        record = SeqIO.read(gbk_path, "genbank")
        features_to_plot = []
        for feat in record.features:
            if feat.type == "CDS":
                gen_txt = str(feat.qualifiers)
                clase_gen = clasificar_gen_ontologia_estricta(gen_txt, feat.qualifiers.get('gene_kind', [''])[0].lower())

                # Colores por categoría funcional
                if clase_gen == 'Core': col = "#E74C3C"
                elif clase_gen == 'Accessory': col = "#2ECC71"
                elif clase_gen == 'Transporter': col = "#3498DB"
                elif clase_gen == 'Regulator': col = "#F1C40F"
                else: col = "#BDC3C7"

                label = feat.qualifiers.get('gene', feat.qualifiers.get('locus_tag', ['']))[0]
                features_to_plot.append(GraphicFeature(start=int(feat.location.start),
                                                       end=int(feat.location.end),
                                                       strand=feat.location.strand,
                                                       color=col, label=label))

        graf_record = GraphicRecord(sequence_length=len(record), features=features_to_plot)
        fig, ax = plt.subplots(figsize=(12, 3))
        graf_record.plot(ax=ax)
        plt.title(f"Functional Architecture (Singleton): {os.path.basename(gbk_path)}", pad=20)
        fig.savefig(output_svg, bbox_inches='tight', format='svg')
        plt.close(fig)
    except Exception as e:
        print(f"  [!] No se pudo dibujar el Singleton {gbk_path}: {e}")

# =====================================================================
# Pipeline principal
# =====================================================================

print("Paso 1: Extrayendo genomas y parseando BGCs...")
for zip_file in glob.glob(os.path.join(PATH_DRIVE, '*.zip')):
    sp_name = os.path.basename(zip_file).replace('.zip', '')
    sp_dir = os.path.join(PATH_WORK, sp_name)
    os.makedirs(sp_dir, exist_ok=True)
    with zipfile.ZipFile(zip_file, 'r') as z:
        z.extractall(sp_dir)

datos_bgc = []
fasta_records_cdhit = []
dict_protein_sequences = {}

especies_extraidas = [d for d in os.listdir(PATH_WORK) if os.path.isdir(os.path.join(PATH_WORK, d))]

for nombre_especie in especies_extraidas:
    ruta_especie = os.path.join(PATH_WORK, nombre_especie)

    for gbk in glob.glob(os.path.join(ruta_especie, "**", "*region*.gbk"), recursive=True):
        try:
            record = SeqIO.read(gbk, "genbank")
            mibig_id, similitud = minar_raw_mibig(gbk)

            # Extraer producto y manejar clusters híbridos
            raw_product = "Unknown"
            for feat in record.features:
                if feat.type in ['region', 'cluster']:
                    productos = feat.qualifiers.get('product', [raw_product])
                    raw_product = "-".join(productos)
                    break

            clean_product = raw_product.replace('-like', '_like').replace(' ', '')
            if '-' in clean_product or ',' in clean_product:
                categoria_cluster, subtipo = "Hybrid", raw_product
            else:
                categoria_cluster, subtipo = raw_product.capitalize(), raw_product

            counts = {"Total_Genes": 0, "Core_Genes": 0, "Accessory_Genes": 0, "Transporters": 0, "Regulators": 0, "Others": 0}
            dominios_set = set()
            dominios_core_set = set()
            prot_sec_core, prot_sec_fallback = "", ""

            # Conteo de genes y extracción de dominios
            for feat in record.features:
                if feat.type == "CDS":
                    counts["Total_Genes"] += 1
                    gen_txt = str(feat.qualifiers)
                    gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()

                    dominios_gen = []
                    if 'sec_met_domain' in feat.qualifiers:
                        dominios_gen.extend(feat.qualifiers['sec_met_domain'])
                    elif 'gene_functions' in feat.qualifiers:
                        for gf in feat.qualifiers['gene_functions']:
                            clean_gf = gf.replace("biosynthetic-additional (smcogs) ", "").replace("other (smcogs) ", "")
                            dominios_gen.append(clean_gf)
                    elif 'NRPS_PKS' in feat.qualifiers:
                        dominios_gen.extend([d for d in feat.qualifiers['NRPS_PKS'] if "Domain:" in d])

                    if not dominios_gen:
                        raw_pfams = re.findall(r'PF\d{5}', gen_txt, re.IGNORECASE) + re.findall(r'PFAM\d{5}', gen_txt, re.IGNORECASE)
                        dominios_gen.extend([p.upper().replace('PFAM', 'PF') for p in raw_pfams])

                    dominios_gen = [" ".join(d.split()) for d in dominios_gen]
                    dominios_set.update(dominios_gen)

                    traduccion = feat.qualifiers.get('translation', [''])[0]
                    if len(traduccion) > len(prot_sec_fallback): prot_sec_fallback = traduccion

                    clase_gen = clasificar_gen_ontologia_estricta(gen_txt, gene_kind)

                    if clase_gen == 'Core':
                        counts["Core_Genes"] += 1
                        dominios_core_set.update(dominios_gen)
                        if len(traduccion) > len(prot_sec_core): prot_sec_core = traduccion
                    elif clase_gen == 'Accessory': counts["Accessory_Genes"] += 1
                    elif clase_gen == 'Transporter': counts["Transporters"] += 1
                    elif clase_gen == 'Regulator': counts["Regulators"] += 1
                    else: counts["Others"] += 1

                    if traduccion:
                        prot_id = f"{nombre_especie}_{os.path.basename(gbk)}_{feat.qualifiers.get('locus_tag', ['ND'])[0]}"
                        dict_protein_sequences[prot_id] = SeqRecord(Seq(traduccion), id=prot_id, description=f"[{clase_gen}]")

            # Normalizar conteo de core genes si hay más de 1 en no-híbridos
            if categoria_cluster != "Hybrid" and counts["Core_Genes"] > 1:
                exceso_core = counts["Core_Genes"] - 1
                counts["Core_Genes"] = 1
                counts["Accessory_Genes"] += exceso_core

            bgc_id = f"{nombre_especie}_{os.path.basename(gbk)}"
            secuencia_final = prot_sec_core if prot_sec_core else prot_sec_fallback

            if secuencia_final:
                fasta_records_cdhit.append(SeqRecord(Seq(secuencia_final), id=bgc_id, description=""))

            if dominios_core_set:
                dominios_core_final = " | ".join(sorted(list(dominios_core_set)))
            elif secuencia_final:
                print(f"  -> Buscando dominios core online para {bgc_id}...")
                dominios_core_final = buscar_pfam_online(secuencia_final)
                if dominios_core_final not in ["No_Pfam_Hits", "Invalid_Sequence", "Network_Timeout", "Not_Annotatable_Online"]:
                    dominios_set.update(dominios_core_final.split(" | "))
            else:
                dominios_core_final = "Not_Annotated_No_Sequence"

            datos_bgc.append({
                "Species": nombre_especie, "BGC_ID": bgc_id, "Category": categoria_cluster,
                "Original_Subtype": subtipo, "MIBiG_Hit": mibig_id, "MIBiG_Identity_%": similitud,
                "Total_Identified_Domains": " | ".join(sorted(list(dominios_set))) if dominios_set else "None",
                "Core_Identified_Domains": dominios_core_final,
                "Core_Sequence": secuencia_final,
                **counts
            })

            # Preparar GBK para Clinker (limpiar metadata para evitar nombres duplicados en los plots)
            record.id = bgc_id
            record.name = bgc_id[:16]
            record.description = ""
            record.annotations.pop('organism', None)
            record.annotations.pop('source', None)
            SeqIO.write(record, os.path.join(PATH_CLINKER, f"{bgc_id}.gbk"), "genbank")

        except Exception: pass

fasta_path_global = "/content/cores_bgcs.fasta"
SeqIO.write(fasta_records_cdhit, fasta_path_global, "fasta")

print("\nPaso 2: Ejecutando CD-HIT para generar familias homólogas...")
subprocess.run(f"cd-hit -i {fasta_path_global} -o /content/bgcs_clustered -c 0.7 -n 4 -d 0 -M 0 -G 0 -aS 0.6", shell=True, check=True, capture_output=True)

familias_reales = {}
with open("/content/bgcs_clustered.clstr", "r") as f:
    cluster_actual = ""
    for linea in f:
        if linea.startswith(">"): cluster_actual = f"Fam_{linea.strip().replace('>', '').replace(' ', '_')}"
        else:
            bgc_id = linea.split(">")[1].split("...")[0]
            familias_reales[bgc_id] = cluster_actual

df_master = pd.DataFrame(datos_bgc)
df_master["Homology_Family"] = df_master["BGC_ID"].map(familias_reales).fillna("Orphan")

for idx, row in df_master.iterrows():
    carpeta_clinker = os.path.join(PATH_CLINKER, row["Homology_Family"])
    os.makedirs(carpeta_clinker, exist_ok=True)
    ruta_gbk = os.path.join(PATH_CLINKER, f"{row['BGC_ID']}.gbk")
    if os.path.exists(ruta_gbk):
        shutil.move(ruta_gbk, os.path.join(carpeta_clinker, f"{row['BGC_ID']}.gbk"))

todas_las_especies = df_master['Species'].unique()
total_sp = len(todas_las_especies)

print("\nPaso 3: Analizando conservación y generando gráficos por categoría...")

df_resumen_clases = pd.crosstab(df_master['Species'], df_master['Category'])
df_resumen_clases.to_excel(os.path.join(PATH_RESULTS, "0_Resumen_Clases_por_Especie.xlsx"))

plt.figure(figsize=(12, 8))
df_resumen_clases.plot(kind='bar', stacked=True, colormap='tab20', ax=plt.gca())
plt.title("Biosynthetic Capacity by Species", fontsize=16, pad=20)
plt.ylabel("Number of Identified BGCs", fontsize=12)
plt.xlabel("Isolate / Species", fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title="Metabolite Type", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig(os.path.join(PATH_RESULTS, "0_Figura_Composicion_General.svg"), format='svg')
plt.close()

for tipo in df_master['Category'].unique():
    print(f"  Procesando: {tipo}")
    ruta_tipo = os.path.join(PATH_RESULTS, f"Category_{tipo}")
    os.makedirs(ruta_tipo, exist_ok=True)

    df_tipo = df_master[df_master['Category'] == tipo]

    cols = ["Species", "BGC_ID", "Category", "Original_Subtype", "MIBiG_Hit", "MIBiG_Identity_%",
            "Total_Genes", "Core_Genes", "Accessory_Genes", "Transporters", "Regulators",
            "Others", "Total_Identified_Domains", "Core_Identified_Domains", "Homology_Family"]
    df_tipo[cols].to_excel(os.path.join(ruta_tipo, f"1_Anatomy_{tipo}.xlsx"), index=False)

    matriz_pa = pd.crosstab(df_tipo['Species'], df_tipo['Homology_Family'])
    matriz_pa = matriz_pa.reindex(todas_las_especies, fill_value=0)
    matriz_pa.to_excel(os.path.join(ruta_tipo, f"2_PA_Matrix_{tipo}.xlsx"))

    stats = []
    path_core = os.path.join(ruta_tipo, "Synteny_STRICT_CORE")
    path_sing = os.path.join(ruta_tipo, "Synteny_EXCLUSIVE_SINGLETON")

    for familia in matriz_pa.columns:
        n_sp = (matriz_pa[familia] > 0).sum()
        ruta_origen = os.path.join(PATH_CLINKER, familia)

        if n_sp == total_sp:
            estado = "Strict Core"
            os.makedirs(path_core, exist_ok=True)
            # Sintenia interactiva con Clinker
            archivo_salida = os.path.join(path_core, f"Synteny_CORE_{familia}.html")
            os.system(f"clinker {ruta_origen}/*.gbk -p {archivo_salida} -i 0.4")

        elif n_sp == 1:
            estado = "Specific Singleton"
            os.makedirs(path_sing, exist_ok=True)

            datos_fam = df_tipo[df_tipo['Homology_Family'] == familia].iloc[0]
            gbk_singleton = os.path.join(ruta_origen, f"{datos_fam['BGC_ID']}.gbk")
            archivo_salida_svg = os.path.join(path_sing, f"Architecture_SINGLETON_{familia}.svg")

            dibujar_singleton_funcional(gbk_singleton, archivo_salida_svg)

        else:
            estado = f"Accessory ({n_sp}/{total_sp})"

        stats.append({"Homology_Family": familia, "Prevalence": f"{n_sp}/{total_sp}", "Evolutionary_State": estado})

    pd.DataFrame(stats).to_excel(os.path.join(ruta_tipo, f"3_Conservation_{tipo}.xlsx"), index=False)

    if USE_UPSET:
        if len(matriz_pa.index) > 1 and len(matriz_pa.columns) > 0:
            try:
                df_upset_bool = (matriz_pa > 0).astype(bool).T
                df_upset_counts = df_upset_bool.groupby(list(df_upset_bool.columns)).size()

                plt.figure(figsize=(10, 6))
                upset_plot(df_upset_counts, sort_by='cardinality', show_counts=True)
                plt.title(f"BGC Pangenomic Intersection - Category: {tipo}", pad=20)
                plt.savefig(os.path.join(ruta_tipo, f"4_UpSet_Plot_{tipo}.svg"), format='svg', bbox_inches='tight')
                plt.close()
            except Exception as e:
                print(f"  [!] Fallo al generar UpSet plot para {tipo}: {e}")
                plt.close()

print("\nPaso 4: Exportando datos para modelos predictivos...")
path_ml_excel = os.path.join(PATH_RESULTS, "Data_Machine_Learning_ML.xlsx")
path_ml_pkl = os.path.join(PATH_RESULTS, "Data_Machine_Learning_ML.pkl")

df_master.to_excel(path_ml_excel, index=False)
df_master.to_pickle(path_ml_pkl)
print(f"  -> Archivos guardados: .xlsx y .pkl")

print("\nAnálisis finalizado. Los resultados se han guardado en el directorio de salida.")

"""**Módulo 2: Pangenómica de BGCs, Análisis de Sintenia Comparativa y Visualización de Arquitecturas Singulares**

Este bloque procesa el espacio genómico secundario bajo un enfoque pangenómico para evaluar la conservación molecular e interconectar variantes estructurales entre cepas.

Clustering Homólogo por CD-HIT: Extrae las secuencias peptídicas de los genes biosintéticos core de mayor longitud e implementa el algoritmo de agrupamiento ultrarrápido CD-HIT (parámetros críticos: -c 0.7 -n 4), lo que permite clasificar los BGCs en "Familias de Homología" inter-cepa.

Modelado del Espacio Pangenómico: Construye matrices globales de presencia/ausencia para cada categoría metabólica (NRPS, PKS, Terpenos, etc.) y evalúa la prevalencia de cada familia, catalogándola en compartimentos pangenómicos definidos (Strict Core, Accessory o Specific Singleton).

Análisis Sinténico Dinámico con Clinker: Para aquellos grupos categorizados como estructuralmente conservados en toda la población genómica (Strict Core), el sistema automatiza la ejecución de Clinker con un umbral de identidad estricto (-i 0.4), generando diagramas sinténicos dinámicos e interactivos en HTML para el estudio de reordenamientos cromosómicos.

Visualización de Arquitecturas Exclusivas: Para variantes metabólicas únicas de un solo aislamiento (Specific Singletons), implementa el renderizado vectorial automatizado en formato SVG mediante DNA Features Viewer, mapeando con código de colores la orientación funcional exacta del locus biosintético.

Intersección Multidimensional: Utiliza la librería UpSetPlot para graficar la intersección combinatoria de las familias homólogas, superando las limitaciones de los diagramas de Venn tradicionales para analizar el solapamiento molecular masivo.
"""

import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

try:
    import openpyxl
    from upsetplot import plot as upset_plot
except ImportError:
    os.system("pip install openpyxl upsetplot")
    import openpyxl
    from upsetplot import plot as upset_plot

warnings.filterwarnings('ignore')

# -----------------------------------------------------------------------------
# 1. PATHS AND ENVIRONMENT SETTINGS
# -----------------------------------------------------------------------------
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    BASE_PATH = "/content/drive/MyDrive/TFM"
except ImportError:
    BASE_PATH = "./TFM"

DIR_DIAMOND = os.path.join(BASE_PATH, "archivos_diamond")
DIR_EGGNOG = os.path.join(BASE_PATH, "archivos_eggnogg")

OUT_FIGS = os.path.join(BASE_PATH, "Results_Publication_SVG_English")
OUT_TABS = os.path.join(BASE_PATH, "Results_Publication_Excel_English")
OUT_ML = os.path.join(BASE_PATH, "Results_Machine_Learning_English")

for d in [OUT_FIGS, OUT_TABS, OUT_ML]:
    os.makedirs(d, exist_ok=True)

UMBRAL_ID = 70.0

# Official COG Dictionary mapped exactly for both Heatmap and UpSet Plot
COG_DICT = {
    'J': 'Translation & Ribosomes', 'A': 'RNA processing', 'K': 'Transcription',
    'L': 'Replication & Repair', 'B': 'Chromatin structure', 'D': 'Cell cycle control',
    'V': 'Defense mechanisms', 'T': 'Signal transduction', 'M': 'Cell wall membrane',
    'N': 'Cell motility', 'Z': 'Cytoskeleton', 'W': 'Extracellular structures',
    'O': 'Posttranslational mod', 'C': 'Energy production', 'G': 'Carbohydrate metabolism',
    'E': 'Amino acid metabolism', 'F': 'Nucleotide metabolism', 'H': 'Coenzyme metabolism',
    'I': 'Lipid metabolism', 'P': 'Inorganic ion metabolism', 'Q': 'Secondary metabolites',
    'R': 'General function prediction', 'S': 'Function unknown'
}

EC_CLASSES = {
    '1': '1. Oxidoreductases', '2': '2. Transferases', '3': '3. Hydrolases',
    '4': '4. Lyases', '5': '5. Isomerases', '6': '6. Ligases', '7': '7. Translocases'
}

# -----------------------------------------------------------------------------
# BLOCK 1: DIAMOND PROCESSING (SECRETOME EVOLUTIONARY BINS)
# -----------------------------------------------------------------------------
def procesar_diamond():
    print("\n[1/4] Processing Secretome Evolutionary Architecture (DIAMOND)...")
    archivos = glob.glob(os.path.join(DIR_DIAMOND, "*.txt")) + glob.glob(os.path.join(DIR_DIAMOND, "*.tsv"))
    if not archivos: return pd.DataFrame()

    lista_raw = []
    lista_stats = []

    for archivo in archivos:
        cepa = os.path.basename(archivo).split('.')[0].split('_')[0]
        try:
            df = pd.read_csv(archivo, sep='\t')
            df = df.iloc[:, :5]
            df.columns = ['qseqid', 'sseqid', 'evalue', 'bitscore', 'pident']
            df['pident'] = pd.to_numeric(df['pident'], errors='coerce')
            df['evalue'] = pd.to_numeric(df['evalue'], errors='coerce')
            df = df.dropna(subset=['pident', 'evalue'])

            df_filt = df[(df['evalue'] < 1e-10) & (df['pident'] >= UMBRAL_ID)].copy()
            df_filt['Strain'] = cepa

            bins = [70, 80, 90, 100.1]
            labels = ['Divergent (70-80%)', 'Conserved (80-90%)', 'High Identity (>90%)']
            df_filt['Evolutionary_Range'] = pd.cut(df_filt['pident'], bins=bins, labels=labels, right=False)

            lista_raw.append(df_filt)
            lista_stats.append({
                'Strain': cepa, 'Homologues (>=70%)': len(df_filt),
                'Mean Identity (%)': round(df_filt['pident'].mean(), 2)
            })
        except Exception as e:
            print(f"  ❌ Error in DIAMOND {cepa}: {e}")

    df_maestro = pd.concat(lista_raw)
    pd.DataFrame(lista_stats).to_excel(os.path.join(OUT_TABS, "Table_1_DIAMOND_Stats.xlsx"), index=False)

    # Fig 1A: Stacked Bar Chart
    plt.close('all')
    sns.set_theme(style="ticks", context="paper", font_scale=1.2)
    prop = df_maestro.groupby(['Strain', 'Evolutionary_Range']).size().unstack().fillna(0)
    prop_pct = prop.div(prop.sum(axis=1), axis=0) * 100

    ax = prop_pct.plot(kind='bar', stacked=True, figsize=(8, 6), color=['#e76f51', '#f4a261', '#2a9d8f'], width=0.6)
    plt.title('Evolutionary Profile of the Secretome (Fig 1A)', pad=15, fontweight='bold')
    plt.ylabel('Secretome Proportion (%)', fontweight='bold')
    plt.xlabel('Strain', fontweight='bold')
    plt.xticks(rotation=0)
    plt.legend(title='Conservation Range', bbox_to_anchor=(1.05, 1), loc='upper left', frameon=False)
    sns.despine()
    plt.savefig(os.path.join(OUT_FIGS, "Fig_1A_Secretome_Evolutionary_Ranges.svg"), format='svg', bbox_inches='tight')
    plt.close()

    # Fig 1B: UpSet Plot (CORREGIDO)
    matriz_dianas = pd.crosstab(df_maestro['sseqid'], df_maestro['Strain'])
    matriz_dianas_bool = (matriz_dianas > 0).astype(bool)

    upset_data = matriz_dianas_bool.groupby(list(matriz_dianas_bool.columns)).size()

    # Renderizado seguro para UpSetPlot
    fig = plt.figure(figsize=(12, 8))
    upset_plot(upset_data, sort_by='cardinality', show_counts=True, fig=fig)
    plt.suptitle('Intersection of Secreted Homologous Targets (Fig 1B)', fontweight='bold', fontsize=14, y=1.05)
    plt.savefig(os.path.join(OUT_FIGS, "Fig_1B_Secretome_Targets_UpSet.svg"), format='svg', bbox_inches='tight')
    plt.close(fig)

    return df_maestro

# -----------------------------------------------------------------------------
# BLOCK 2: EGGNOG PROCESSING (COG, EC, OGs for ML)
# -----------------------------------------------------------------------------
def procesar_eggnog():
    print("\n[2/4] Processing Functional Profiling (eggNOG)...")
    archivos = glob.glob(os.path.join(DIR_EGGNOG, "*.txt")) + glob.glob(os.path.join(DIR_EGGNOG, "*.annotations*"))
    if not archivos: return pd.DataFrame(), pd.DataFrame()

    lista_cogs, lista_ecs, lista_ogs_ml, lista_raw = [], [], [], []

    for archivo in archivos:
        cepa = os.path.basename(archivo).split('.')[0].split('_')[0]
        try:
            df = pd.read_csv(archivo, sep='\t', comment='#', header=None, low_memory=False)
            df.columns = ['query', 'seed', 'evalue', 'score', 'OGs', 'tax', 'COG_cat', 'desc', 'name', 'GO', 'EC', 'KO', 'Path', 'Mod', 'React', 'Rclass', 'BRITE', 'TC', 'CAZy', 'BiGG', 'PFAMs'][:len(df.columns)]
            df['Strain'] = cepa
            lista_raw.append(df)

            # Extract COG and OG for Orthology Integration (CORREGIDO)
            if 'COG_cat' in df.columns and 'OGs' in df.columns:
                for _, row in df[['query', 'COG_cat', 'OGs']].dropna().iterrows():
                    # Extraer el Grupo Ortólogo principal para poder encontrar intersecciones inter-cepa
                    og_principal = str(row['OGs']).split(',')[0]
                    for letra in str(row['COG_cat']):
                        if letra in COG_DICT:
                            lista_cogs.append({
                                'Strain': cepa,
                                'COG_Category': COG_DICT[letra],
                                'Code': letra,
                                'Query_ID': row['query'],
                                'OG': og_principal # Usaremos esto para el UpSet Plot
                            })

            # Extract EC
            if 'EC' in df.columns:
                for _, row in df[['query', 'EC']].dropna().iterrows():
                    for ec in str(row['EC']).split(','):
                        ec_clean = ec.strip()
                        ec_main = ec_clean.split('.')[0]
                        if ec_main in EC_CLASSES:
                            lista_ecs.append({'Strain': cepa, 'EC_Number': ec_clean, 'EC_Class': EC_CLASSES[ec_main]})

            if 'OGs' in df.columns:
                ogs = df[['query', 'OGs']].dropna()
                ogs = ogs[ogs['OGs'] != '-']
                ogs['Strain'] = cepa
                lista_ogs_ml.append(ogs)

        except Exception as e:
            print(f"  ❌ Error in eggNOG {cepa}: {e}")

    df_eggnog_completo = pd.concat(lista_raw)

    # --- COG VISUALIZATIONS ---
    df_cogs = pd.DataFrame(lista_cogs)
    if not df_cogs.empty:
        df_cogs_clean = df_cogs[~df_cogs['Code'].isin(['S', 'R'])]

        # Fig 2A: Heatmap COG
        plt.close('all')
        matriz_cog = pd.crosstab(df_cogs_clean['COG_Category'], df_cogs_clean['Strain'])
        plt.figure(figsize=(10, 8))
        sns.heatmap(matriz_cog, cmap="Blues", annot=True, fmt="d", linewidths=.5)
        plt.title('Biological COG Categories Distribution (Fig 2A)', pad=15, fontweight='bold')
        plt.ylabel('COG Category', fontweight='bold')
        plt.yticks(rotation=0)
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2A_COG_Heatmap.svg"), format='svg', bbox_inches='tight')
        plt.close()

        # Fig 2B: UPSET PLOTS POR CADA CATEGORIA COG (CORREGIDO)
        print("      Generating specific UpSet plots for each COG category...")
        for cat in df_cogs_clean['COG_Category'].unique():
            df_cat = df_cogs_clean[df_cogs_clean['COG_Category'] == cat]
            # Usar 'OG' en lugar de 'Query_ID' permite encontrar las dianas compartidas
            matriz_upset = pd.crosstab(df_cat['OG'], df_cat['Strain'])
            matriz_bool = (matriz_upset > 0).astype(bool)

            if len(matriz_bool.columns) > 1:
                try:
                    upset_data_cog = matriz_bool.groupby(list(matriz_bool.columns)).size()
                    fig = plt.figure(figsize=(10, 6))
                    upset_plot(upset_data_cog, sort_by='cardinality', show_counts=True, fig=fig)
                    plt.suptitle(f'Ortholog Intersection: {cat}', fontweight='bold', fontsize=12, y=1.05)
                    cat_safe = cat.replace('/', '_').replace(' ', '_').replace('(', '').replace(')', '').replace('&', 'and')
                    plt.savefig(os.path.join(OUT_FIGS, f"Fig_2B_UpSet_COG_{cat_safe}.svg"), format='svg', bbox_inches='tight')
                    plt.close(fig)
                except Exception as e:
                    pass

    # --- ENZYME (EC) VISUALIZATIONS ---
    df_ecs = pd.DataFrame(lista_ecs)
    if not df_ecs.empty:
        # Fig 2C: UpSet Plot EC Numbers (Aplicando renderizado seguro)
        matriz_ec = pd.crosstab(df_ecs['EC_Number'], df_ecs['Strain'])
        matriz_ec_bool = (matriz_ec > 0).astype(bool)
        upset_data_ec = matriz_ec_bool.groupby(list(matriz_ec_bool.columns)).size()

        fig3 = plt.figure(figsize=(12, 8))
        upset_plot(upset_data_ec, sort_by='cardinality', show_counts=True, fig=fig3)
        plt.suptitle('Enzymatic Repertoire Intersection (Fig 2C)', fontweight='bold', fontsize=14, y=1.05)
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2C_Enzymes_UpSet.svg"), format='svg', bbox_inches='tight')
        plt.close(fig3)

        # Fig 2D: EC Classes Bar Chart
        plt.close('all')
        matriz_ec_classes = pd.crosstab(df_ecs['EC_Class'], df_ecs['Strain'])
        matriz_ec_classes.plot(kind='bar', figsize=(10, 6), colormap='viridis', width=0.7)
        plt.title('Distribution of Main Enzyme Classes (Fig 2D)', pad=15, fontweight='bold')
        plt.ylabel('Number of Enzymes', fontweight='bold')
        plt.xlabel('Enzyme Class', fontweight='bold')
        plt.xticks(rotation=45, ha='right')
        sns.despine()
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2D_EC_Classes.svg"), format='svg', bbox_inches='tight')
        plt.close()

    if not df_cogs.empty: pd.crosstab(df_cogs['COG_Category'], df_cogs['Strain']).to_excel(os.path.join(OUT_TABS, "Table_S2A_COG_Full.xlsx"))
    if not df_ecs.empty: matriz_ec.to_excel(os.path.join(OUT_TABS, "Table_S2B_EC_Matrix.xlsx"))

    # ML Predictors
    df_ml_raw = pd.concat(lista_ogs_ml)
    df_ml_raw['Predictor_ID'] = "eggNOG_" + df_ml_raw['OGs'].apply(lambda x: str(x).split(',')[0])
    matriz_pa_eggnog = pd.crosstab(df_ml_raw['Predictor_ID'], df_ml_raw['Strain'])
    matriz_pa_eggnog = (matriz_pa_eggnog > 0).astype(int)

    return df_eggnog_completo, matriz_pa_eggnog

# -----------------------------------------------------------------------------
# BLOCK 3: SECRETOME ECOLOGICAL FRACTIONATION
# -----------------------------------------------------------------------------
def clasificar_secretoma(row):
    cazy = str(row.get('CAZy', '-'))
    pfam = str(row.get('PFAMs', '-')).lower()
    desc = str(row.get('desc', '-')).lower()
    if cazy != '-': return 'CAZymes (PCW Degradation)'
    elif any(x in pfam or x in desc for x in ['peptidase', 'protease']): return 'Proteases / Peptidases'
    elif any(x in pfam or x in desc for x in ['lipase', 'esterase']): return 'Lipases / Esterases'
    elif 'oxidoreductase' in pfam or 'oxidoreductase' in desc: return 'Oxidoreductases'
    elif row.get('evalue', 1) > 1e-10: return 'Putative Specific Effectors'
    else: return 'Other Secreted Proteins'

def fraccionar_secretoma(df_diam, df_egg):
    print("\n[3/4] Fractionating Secretome Arsenal (DIAMOND + eggNOG)...")
    if df_diam.empty or df_egg.empty: return

    df_diam['Clean_ID'] = df_diam['qseqid'].str.split('.').str[0]
    df_egg['Clean_ID'] = df_egg['query'].str.split('.').str[0]

    df_cruce = pd.merge(df_diam, df_egg, on=['Clean_ID', 'Strain'], how='inner')
    df_cruce['Macro_Category'] = df_cruce.apply(clasificar_secretoma, axis=1)

    matriz_cat = pd.crosstab(df_cruce['Macro_Category'], df_cruce['Strain'])

    # Fig 3A: Heatmap
    plt.close('all')
    plt.figure(figsize=(10, 8))
    sns.heatmap(matriz_cat, cmap="YlOrRd", annot=True, fmt="d", linewidths=1)
    plt.title('Functional Architecture of the Secretome (Fig 3A)', fontsize=15, pad=20, fontweight='bold')
    plt.ylabel('Biological Macro-Category', fontweight='bold')
    plt.yticks(rotation=0)
    plt.savefig(os.path.join(OUT_FIGS, "Fig_3A_Secretome_Heatmap.svg"), format='svg', bbox_inches='tight')
    plt.close()

    # Fig 3B: CAZymes Breakdown
    cazy_list = []
    for _, row in df_cruce[df_cruce['CAZy'] != '-'].iterrows():
        for cz in str(row['CAZy']).split(','):
            clase = ''.join(filter(str.isalpha, cz.strip()))
            if clase: cazy_list.append({'Strain': row['Strain'], 'CAZy_Class': clase})

    if cazy_list:
        plt.close('all')
        df_cazy = pd.DataFrame(cazy_list)
        cazy_counts = pd.crosstab(df_cazy['CAZy_Class'], df_cazy['Strain'])
        cazy_counts.plot(kind='bar', figsize=(9, 6), colormap='Set2', width=0.7)
        plt.title('Distribution of Secreted CAZyme Families (Fig 3B)', pad=15, fontweight='bold')
        plt.ylabel('Number of Domains', fontweight='bold')
        plt.xlabel('CAZy Class', fontweight='bold')
        plt.xticks(rotation=0)
        sns.despine()
        plt.savefig(os.path.join(OUT_FIGS, "Fig_3B_Secretome_CAZymes.svg"), format='svg', bbox_inches='tight')
        plt.close()

    # Fig 3C-X: UpSet Plots per Macro-Category (Aplicando renderizado seguro)
    print("      Generating specific UpSet plots for each Secretome category...")
    for idx, cat in enumerate(df_cruce['Macro_Category'].unique()):
        df_cat = df_cruce[df_cruce['Macro_Category'] == cat]
        matriz_upset = pd.crosstab(df_cat['sseqid'], df_cat['Strain'])
        matriz_bool = (matriz_upset > 0).astype(bool)

        if len(matriz_bool.columns) > 1:
            try:
                upset_data_cat = matriz_bool.groupby(list(matriz_bool.columns)).size()
                fig = plt.figure(figsize=(10, 6))
                upset_plot(upset_data_cat, sort_by='cardinality', show_counts=True, fig=fig)
                plt.suptitle(f'Target Intersection: {cat}', fontweight='bold', fontsize=12, y=1.05)
                cat_safe = cat.replace('/', '_').replace(' ', '_').replace('(', '').replace(')', '')
                plt.savefig(os.path.join(OUT_FIGS, f"Fig_3C_UpSet_{cat_safe}.svg"), format='svg', bbox_inches='tight')
                plt.close(fig)
            except Exception as e:
                pass

    cols_out = ['Strain', 'qseqid', 'Macro_Category', 'sseqid', 'pident', 'CAZy', 'PFAMs', 'desc']
    df_cruce[cols_out].to_excel(os.path.join(OUT_TABS, "Table_S1_Master_Secretome.xlsx"), index=False)


# -----------------------------------------------------------------------------
# BLOCK 4: ML SUPER-MATRIX ASSEMBLY
# -----------------------------------------------------------------------------
def ensamblar_ml(m_egg):
    print("\n[4/4] Assembling Predictive Super-Matrix for Machine Learning...")
    matrices = [m for m in [m_egg] if not m.empty]
    if not matrices: return

    matriz_maestra = pd.concat(matrices, axis=0, join='outer').fillna(0).astype(int)
    n_cepas = len(matriz_maestra.columns)
    matriz_maestra['Sum'] = matriz_maestra.sum(axis=1)

    matriz_filtrada = matriz_maestra[(matriz_maestra['Sum'] > 0) & (matriz_maestra['Sum'] < n_cepas)].drop(columns=['Sum'])
    dataset_xgboost = matriz_filtrada.T
    ruta_ml = os.path.join(OUT_ML, "Table_S3_DATASET_XGBOOST.csv")
    dataset_xgboost.to_csv(ruta_ml, index_label="Strain_Sample")

    # Fig 4: Horizontal Bar Chart of Predictors Origin
    plt.close('all')
    sns.set_theme(style="ticks", context="paper", font_scale=1.2)

    origenes = matriz_filtrada.index.to_series().str.split('_').str[0].value_counts()

    plt.figure(figsize=(10, 6))
    ax = sns.barplot(x=origenes.values, y=origenes.index, palette='viridis')
    plt.title('Accessory Genome Architecture (ML Predictors Origin) - Fig 4', pad=15, fontweight='bold')
    plt.xlabel('Number of Features (Genes/Clusters)', fontweight='bold')
    plt.ylabel('Omics Dimension', fontweight='bold')
    sns.despine()

    plt.savefig(os.path.join(OUT_FIGS, "Fig_4_ML_Predictors_BarChart.svg"), format='svg', bbox_inches='tight')
    plt.close()

    print(f"  ✅ Super-Matrix Generated: {dataset_xgboost.shape[1]} predictors for {dataset_xgboost.shape[0]} strains.")

# -----------------------------------------------------------------------------
# MAIN EXECUTION
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    df_diam = procesar_diamond()
    df_egg, matriz_egg = procesar_eggnog()

    fraccionar_secretoma(df_diam, df_egg)

    ensamblar_ml(matriz_egg)

    print("\n🚀 PIPELINE COMPLETED. All Q1 English Figures and Tables are ready.")

"""##Matriz de Solapamiento Recíproco del Pangenoma (Heatmap)
**Descripción:**
Este script automatiza el procesamiento y la visualización de la matriz de presencia/ausencia global generada por OrthoFinder. Su objetivo es calcular y mapear el número total de ortogrupos proteicos homólogos compartidos de forma recíproca (par a par) entre los proteomas completos de las 18 especies del género *Botrytis*.

**Características del análisis:**
*   **Mapeo Taxonómico:** Traduce de forma automática los códigos internos de los archivos raw (`Bcine`, `Bacla`, etc.) a la nomenclatura binomial científica formal en cursiva.
*   **Anotación Cuantitativa:** Añade las etiquetas con los valores absolutos exactos de genes compartidos en cada celda de la matriz.
*   **Exportación Editorial:** Genera y exporta la gráfica final en alta resolución (`Figura_Heatmap_Pangenoma_Completo.jpg`), lista para su incorporación directa en la memoria o material suplementario.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# 1. Ruta de tu archivo en Google Drive
ruta_overlap = '/content/drive/MyDrive/TFM/Galaxy260-[OrthoFinder on dataset 230-247 and collection 229_ species overlaps].tsv'

if not os.path.exists(ruta_overlap):
    print(f"❌ Error: No se encuentra el archivo en la ruta: {ruta_overlap}")
else:
    # Leer matriz original
    df_overlap = pd.read_csv(ruta_overlap, sep='\t', index_col=0)

    # Diccionario de traducción de códigos a nombres científicos completos
    mapeo_especies = {
        'Bcine': 'Botrytis cinerea',
        'Bpseu': 'Botrytis pseudocinerea',
        'Bfaba': 'Botrytis fabae',
        'Bsqua': 'Botrytis squamosa',
        'Bacla': 'Botrytis aclada',
        'Bporr': 'Botrytis porri',
        'Bsino': 'Botrytis sinoallii',
        'Bbyss': 'Botrytis byssoidea',
        'Belli': 'Botrytis elliptica',
        'Btuli': 'Botrytis tulipae',
        'Bpaeo': 'Botrytis paeoniae',
        'Bhyac': 'Botrytis hyacinthi',
        'Bgala': 'Botrytis galanthina',
        'Bdewe': 'Botrytis deweyae',
        'Bfrag': 'Botrytis fragariae',
        'Beuro': 'Botrytis euroamericana',
        'Bmedu': 'Botrytis medusae',
        'Bfabi': 'Botrytis fabiopsis'
    }

    # Renombrar filas y columnas aplicando el mapa taxonómico
    df_overlap = df_overlap.rename(index=mapeo_especies, columns=mapeo_especies)

    # 2. Configuración estética de grado editorial
    fig, ax = plt.subplots(figsize=(15, 13))
    sns.set_theme(style="white")

    # Configuración de renderizado para tipografías vectoriales limpias
    plt.rcParams['svg.fonttype'] = 'none'

    # Dibujar el mapa de calor
    sns.heatmap(
        df_overlap,
        annot=True,
        fmt=".0f",
        cmap="Blues",
        linewidths=.6,
        cbar_kws={'label': 'Número de Ortogrupos Compartidos entre Proteomas'},
        annot_kws={"size": 9, "weight": "bold"}
    )

    # Títulos y formato de ejes
    plt.title("Matriz de Solapamiento del Pangenoma Global de Botrytis\n(Análisis de Homología de Secuencia Completa vía OrthoFinder)",
              fontsize=14, weight='bold', pad=25)
    plt.xlabel("Especies de Botrytis Analizadas", fontsize=12, weight='bold', labelpad=15)
    plt.ylabel("Especies de Botrytis Analizadas", fontsize=12, weight='bold', labelpad=15)

    # ¡Clave! Forzamos que las etiquetas de los ejes salgan en cursiva (itálica) como exige la nomenclatura biológica
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', weight='bold', style='italic', fontsize=11)
    ax.set_yticklabels(ax.get_yticklabels(), weight='bold', style='italic', fontsize=11)

    plt.tight_layout()

    # 3. Exportación simultánea (SVG vectorial para calidad infinita y PNG para vista rápida)
    PATH_RESULTS = os.path.dirname(ruta_overlap)

    ruta_svg = os.path.join(PATH_RESULTS, "Figura_Heatmap_Pangenoma_Completo.svg")
    ruta_png = os.path.join(PATH_RESULTS, "Figura_Heatmap_Pangenoma_Completo.png")

    plt.savefig(ruta_svg, format='svg', bbox_inches='tight')
    plt.savefig(ruta_png, dpi=300, bbox_inches='tight')
    plt.show()

    print("\n[✓] ¡Imágenes generadas con éxito con nomenclatura biológica formal!")
    print(f"💾 Vectorial (SVG) guardado en: {ruta_svg}")
    print(f"💾 Imagen (PNG) guardada en: {ruta_png}")

"""## Compartimentación Molecular del Pangenoma por Especie (Stacked Bar Chart)
**Descripción:**
Este script realiza la disección y cuantificación exacta de la arquitectura del pangenoma global de *Botrytis* a partir de los outputs crudos de OrthoFinder. El algoritmo analiza en paralelo la matriz de ortogrupos (`Galaxy254`) y el reporte de secuencias huérfanas o no asignadas (`Galaxy255`) para clasificar el proteoma completo de cada una de las 18 especies en tres compartimentos moleculares biológicamente independientes.

**Compartimentos analizados:**
1.  **Core Genome (Genoma Núcleo):** Familias de ortólogos altamente conservadas presentes de forma ubicua en el género ($\geq$ 17 especies evaluadas para mitigar sesgos de ensamblaje).
2.  **Accessory Genome (Genoma Accesorio):** Ortogrupos variables presentes en dos o más especies, pero sin llegar a la ubicuidad global (homologías compartidas y parálogos).
3.  **Specific Singletons (Componente Específico):** Genes de copia única exclusivos de cada taxón combinados con los genes huérfanos del reporte de *unassigned genes*.

**Exportación Editorial:** Genera la visualización de barras apiladas con una paleta de grado científico y exporta los resultados en formato vectorial escalable (`Figura_Barras_Pangenoma_Total.svg`) para garantizar una calidad de publicación óptima.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# 1. Definición de rutas a tus archivos reales de OrthoFinder
ruta_orthogroups = '/content/drive/MyDrive/TFM/Galaxy254-[OrthoFinder on dataset 230-247 and collection 229_ orthogroups (tsv)] (1).tsv'
ruta_unassigned = '/content/drive/MyDrive/TFM/Galaxy255-[OrthoFinder on dataset 230-247 and collection 229_ unassigned genes].tsv'

# Mapeo oficial de nombres en cursiva
mapeo_especies = {
    'Bcine': 'Botrytis cinerea', 'Bpseu': 'Botrytis pseudocinerea', 'Bfaba': 'Botrytis fabae',
    'Bsqua': 'Botrytis squamosa', 'Bacla': 'Botrytis aclada', 'Bporr': 'Botrytis porri',
    'Bsino': 'Botrytis sinoallii', 'Bbyss': 'Botrytis byssoidea', 'Belli': 'Botrytis elliptica',
    'Btuli': 'Botrytis tulipae', 'Bpaeo': 'Botrytis paeoniae', 'Bhyac': 'Botrytis hyacinthi',
    'Bgala': 'Botrytis galanthina', 'Bdewe': 'Botrytis deweyae', 'Bfrag': 'Botrytis fragariae',
    'Beuro': 'Botrytis euroamericana', 'Bmedu': 'Botrytis medusae', 'Bfabi': 'Botrytis fabiopsis'
}

if not os.path.exists(ruta_orthogroups) or not os.path.exists(ruta_unassigned):
    print("❌ Error: Verifica que los nombres de los archivos TSV subidos coincidan con las rutas.")
else:
    print("[►] Extrayendo arquitectura real del pangenoma completo...")

    # Cargar archivos de Galaxy
    df_og = pd.read_csv(ruta_orthogroups, sep='\t', index_col=0)
    df_un = pd.read_csv(ruta_unassigned, sep='\t', index_col=0)

    cepas = list(mapeo_especies.keys())

    # 2. Convertir matrices de texto a matrices binarias (1 si hay gen, 0 si está vacío)
    df_og_bin = df_og[cepas].notna().astype(int)
    df_un_bin = df_un[cepas].notna().astype(int)

    # Contar cuántas cepas tienen cada ortogrupo
    frecuencia_og = df_og_bin.sum(axis=1)

    # Clasificación formal de los Ortogrupos
    # Core Estricto (las 18 especies) u opción Soft-Core (>= 17 especies) para mitigar fallos de ensamblaje
    umbral_core = 17

    og_core = df_og_bin[frecuencia_og >= umbral_core]
    og_acc = df_og_bin[(frecuencia_og < umbral_core) & (frecuencia_og > 1)]
    og_sing = df_og_bin[frecuencia_og == 1]

    # Conteo de genes por compartimento para cada especie individual
    datos_grafico = []

    for c in cepas:
        # Contamos cuántas proteínas aporta esta especie a cada tipo de grupo
        # Para hacerlo exacto, extraemos el número real de secuencias (separadas por comas en las celdas del tsv)
        genes_core = df_og.loc[og_core.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        genes_acc = df_og.loc[og_acc.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()

        # Singletons de Ortogrupos específicos + Genes huérfanos unassigned (Galaxy255)
        genes_sing_og = df_og.loc[og_sing.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        genes_sing_un = df_un[c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        total_singletons = genes_sing_og + genes_sing_un

        datos_grafico.append({
            'Especie': mapeo_especies[c],
            'Core Genome': genes_core,
            'Accessory Genome': genes_acc,
            'Specific Singletons': total_singletons
        })

    df_resultados = pd.DataFrame(datos_grafico).set_index('Especie')

    # Mostrar resumen cuantitativo en consola
    print("\n[✓] Análisis molecular completado. Resumen promedidado del Genoma Completo:")
    print(df_resultados.mean().to_string())

    # 3. GENERACIÓN DE LA FIGURA DE BARRAS APILADAS (FORMATO EDITORIAL SVG)
    fig, ax = plt.subplots(figsize=(14, 9))
    plt.rcParams['svg.fonttype'] = 'none'

    # Paleta de grado científico: Azul oscuro (Core), Azul medio (Accesorio), Celeste/Gris claro (Singletons)
    colores = ['#1b365d', '#4b779a', '#aed1e6']

    df_resultados.plot(kind='bar', stacked=True, color=colores, ax=ax, width=0.7, edgecolor='black', linewidth=0.5)

    # Configuración del gráfico
    plt.title("Compartimentación del Pangenoma Global del Género Botrytis\n(Distribución de Genes Totales por Especie)", fontsize=14, weight='bold', pad=20)
    plt.xlabel("Especies Analizadas (Genoma Completo)", fontsize=12, weight='bold', labelpad=15)
    plt.ylabel("Número Total de Genes Anotados", fontsize=12, weight='bold', labelpad=15)

    # Leyenda formal
    plt.legend(['Core Genome (Conservado $\geq$17 spp.)', 'Accessory Genome (Variables)', 'Specific Singletons (Únicos / Huérfanos)'],
               loc='lower left', frameon=True, facecolor='white', edgecolor='none')

    # Forzar nombres científicos en cursiva en el eje X
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', weight='bold', style='italic', fontsize=11)
    plt.yticks(weight='bold')
    plt.grid(axis='y', linestyle='--', alpha=0.5)

    plt.tight_layout()

    # Exportar en SVG y PNG
    PATH_RESULTS = os.path.dirname(ruta_orthogroups)
    ruta_svg = os.path.join(PATH_RESULTS, "Figura_Barras_Pangenoma_Total.svg")
    ruta_png = os.path.join(PATH_RESULTS, "Figura_Barras_Pangenoma_Total.png")

    plt.savefig(ruta_svg, format='svg', bbox_inches='tight')
    plt.savefig(ruta_png, dpi=300, bbox_inches='tight')
    plt.show()

    print(f"\n💾 ¡Figura de barras apiladas guardada en SVG vectorial!: {ruta_svg}")

"""## Consolidación Estructurada de la Anotación Funcional Global (eggNOG-mapper)
**Descripción:** Este script automatiza la unificación y el formateo bioinformático de los reportes funcionales en bruto (`.tabular`) generados de forma individual para cada una de las 18 especies de *Botrytis* mediante la plataforma eggNOG-mapper v2.1.2.

El algoritmo realiza un parseo iterativo de la colección de archivos, aplica un filtro automatizado para remover las líneas de comentarios informáticos iniciales (metadatos encabezados por `#`) y rescata las cabeceras originales del pipeline de Galaxy. Finalmente, clasifica las anotaciones construyendo un único libro de Excel multipestaña donde cada hoja se renombra bajo la estricta nomenclatura binomial científica (*Género especie*), sirviendo como la base de datos funcional curada del proyecto.

**Criterios de Calidad Implementados:**
* **Filtro Homólogo:** Mapeo unívoco de los códigos de cepa crudos (`Bcine`, `Bdewe`, etc.) a sus identidades taxonómicas formales.
* **Limpieza de Ruido:** Eliminación de directivas de ejecución informáticas para conservar únicamente las matrices de anotación de grano fino.
* **Soporte Editorial:** Generación automática de la base de datos en un archivo de Excel consolidado (`Tabla_Suplementaria_S2_Anotacion_GO.xlsx`) listo para su depósito como material suplementario transferible.
"""

import os
import glob
import pandas as pd

# 1. Configuración de rutas dentro de tu Google Drive
CARPETA_EGGNOG = '/content/drive/MyDrive/TFM/eggNOG Mapper on collection 229_ annotations/'
RUTA_SALIDA_EXCEL = '/content/drive/MyDrive/TFM/Tabla_Suplementaria_S3_Anotacion_GO.xlsx'

# Diccionario oficial de mapeo taxonómico formal para renombrar las páginas del PDF/Excel
mapeo_especies = {
    'Bacla': 'Botrytis aclada',
    'Bbyss': 'Botrytis byssoidea',
    'Bcine': 'Botrytis cinerea',
    'Bdewe': 'Botrytis deweyae',
    'Belli': 'Botrytis elliptica',
    'Beuro': 'Botrytis euroamericana',
    'Bfaba': 'Botrytis fabae',
    'Bfabi': 'Botrytis fabiopsis',
    'Bfrag': 'Botrytis fragariae',
    'Bgala': 'Botrytis galanthina',
    'Bhyac': 'Botrytis hyacinthi',
    'Bmedu': 'Botrytis medusae',
    'Bpaeo': 'Botrytis paeoniae',
    'Bporr': 'Botrytis porri',
    'Bpseu': 'Botrytis pseudocinerea',
    'Bsino': 'Botrytis sinoallii',
    'Bsqua': 'Botrytis squamosa',
    'Btuli': 'Botrytis tulipae'
}

# Buscar de forma masiva todos los reportes .tabular o .tsv en la carpeta
archivos_input = glob.glob(os.path.join(CARPETA_EGGNOG, "*.tabular")) + glob.glob(os.path.join(CARPETA_EGGNOG, "*.tsv"))

if len(archivos_input) == 0:
    print(f"❌ Error: No se detectaron archivos .tabular en la ruta especificada: {CARPETA_EGGNOG}")
    print("Por favor, revisa que el nombre de la carpeta en tu Drive coincida exactamente.")
else:
    print(f"[►] Iniciando la unificación de {len(archivos_input)} reportes funcionales...")

    # Abrir el escritor multi-pestaña de Excel
    with pd.ExcelWriter(RUTA_SALIDA_EXCEL, engine='openpyxl') as writer:

        for ruta_archivo in sorted(archivos_input):
            nombre_archivo = os.path.basename(ruta_archivo)

            # Identificar el código de la cepa dentro del nombre del archivo
            cepa_detectada = None
            for codigo in mapeo_especies.keys():
                if codigo in nombre_archivo:
                    cepa_detectada = codigo
                    break

            if cepa_detectada:
                nombre_pestaña = mapeo_especies[cepa_detectada]
                # Limitación técnica de Excel: las pestañas no pueden superar los 31 caracteres
                nombre_pestaña_corta = nombre_pestaña[:31]

                try:
                    # 2. Lectura omitiendo las líneas informáticas de comentarios que empiezan con '#'
                    df_temp = pd.read_csv(ruta_archivo, sep='\t', comment='#', header=None)

                    # 3. Rescate de las cabeceras de columnas reales que eggNOG guarda en la línea '#query'
                    columnas = None
                    with open(ruta_archivo, 'r') as f:
                        for line in f:
                            if line.startswith('#query') or line.startswith('# query'):
                                # Limpiamos el símbolo '#' y el espacio sobrante
                                columnas = line.strip().replace('#', '').strip().split('\t')
                                break

                    # Si las columnas extraídas coinciden con el tamaño de la matriz, las asignamos
                    if columnas and len(columnas) == df_temp.shape[1]:
                        df_temp.columns = columnas
                    else:
                        # Cabecera por defecto en caso de anomalía en el archivo raw
                        df_temp.columns = [f"Col_{i}" for i in range(df_temp.shape[1])]

                    # 4. Guardar los datos limpios en la hoja correspondiente a la especie
                    df_temp.to_excel(writer, sheet_name=nombre_pestaña_corta, index=False)
                    print(f"   ✓ Pestaña consolidada con éxito: {nombre_pestaña} ({df_temp.shape[0]} genes anotados)")

                except Exception as e:
                    print(f"   ⚠️ No se pudo procesar el archivo {nombre_archivo} debido a: {e}")
            else:
                print(f"   ⚠️ Archivo omitido (no corresponde a ninguna de las 18 especies): {nombre_archivo}")

    print(f"\n[✓] ¡Proceso finalizado!")
    print(f"💾 Libro de Excel unificado y guardado en: {RUTA_SALIDA_EXCEL}")

"""**Módulo 3: Reperfilamiento del Secretoma, Clasificación de CAZymas y Caracterización de Determinantes Efectores**

Este módulo se centra en diseccionar los elementos proteicos secretados y los perfiles funcionales globales implicados en la interacción directa con el huésped vegetal.

Contenedores Evolutivos por DIAMOND: Procesa los alineamientos masivos del secretoma mediante DIAMOND, segregando los targets en contenedores evolutivos según su rango de identidad peptídica (Divergent: 70-80%, Conserved: 80-90%, High Identity: >98%) para identificar tasas de divergencia adaptativa rápida.

Anotación Masiva de Ortólogos vía eggNOG: Extrae de forma exhaustiva los Grupos Ortólogos (OGs), anotaciones de la Comisión de Enzimas (EC Numbers) y categorías del catálogo oficial COG (mapeando un diccionario estructurado de 26 categorías funcionales) a partir de los reportes de eggNOG-mapper.

Tipado de Familias CAZyme: Rastrea e integra la abundancia y distribución de enzimas activas sobre carbohidratos (CAZymes), clasificando las secuencias por macro-categorías funcionales para comprender los mecanismos de degradación de la pared celular vegetal.

Visualización e Intersección del Secretoma: Genera diagramas de distribución de clases enzimáticas (Seaborn) y plots de UpSet combinatorios específicos por macro-categoría para revelar qué componentes del repertorio efector y enzimático son cepa-específicos o compartidos.
"""

import os
import warnings
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import IsolationForest

warnings.filterwarnings('ignore')

# 0. CONFIGURACIÓN DEL ENTORNO
print("Conectando al sistema de archivos y configurando directorios...")
os.system("fusermount -u /content/drive 2>/dev/null")
os.system("rm -rf /content/drive")
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

PATH_BASE = '/content/drive/MyDrive/TFM'
PATH_ML_OUT = os.path.join(PATH_BASE, "Modelos_ML")
os.makedirs(PATH_ML_OUT, exist_ok=True)

# 1. CARGA Y CURACIÓN DE DATOS
print("Cargando matrices de pangenoma y metadatos fenotípicos...")
df_anti_raw = pd.read_pickle(os.path.join(PATH_BASE, "antismash/Resultados_Pangenomicos_Final/Data_Machine_Learning_ML.pkl"))
df_egg = pd.read_csv(os.path.join(PATH_BASE, "Results_Machine_Learning/Table_S3_DATASET_XGBOOST.csv"), index_col=0)
df_y = pd.read_csv(os.path.join(PATH_BASE, 'Fenotipo_Multiclase.csv'), index_col=0)

def normalizar_taxonomia(n):
    return str(n).replace("Botrytis_", "B").replace(" ", "").strip()

df_egg.index = [normalizar_taxonomia(x) for x in df_egg.index]
df_anti_raw['Species'] = df_anti_raw['Species'].apply(normalizar_taxonomia)

# Mapeo de cepa a hospedador (Nicho ecológico)
mapa_hospedador = df_y['Fenotipo'].to_dict()

# 2. ESPACIO GENÓMICO CORE (eggNOG) Y DETECCIÓN DE ANOMALÍAS
print("Construyendo espacio genómico basal (eggNOG)...")
X_egg = df_egg.fillna(0)

# Filtro de control de calidad para evitar quimeras o contaminación
iso_v31 = IsolationForest(contamination=0.01, random_state=42)
iso_v31.fit(X_egg)

# 3. ESPACIO DE METABOLISMO SECUNDARIO (antiSMASH - TF-IDF)
print("Construyendo espacio de clusters biosintéticos ponderados (TF-IDF)...")
df_anti_mat = pd.crosstab(df_anti_raw['Species'], df_anti_raw['Homology_Family'])
df_anti_mat = (df_anti_mat > 0).astype(int)
X_anti = df_anti_mat.reindex(X_egg.index, fill_value=0)

# Factor de rareza (IDF) para penalizar familias génicas ubicuas
N_especies = len(X_anti)
prevalencia = X_anti.sum(axis=0)
idf_bgc = {fam: np.log((N_especies + 1) / (p + 1)) + 1 for fam, p in prevalencia.items()}

# Vectorización TF-IDF final
X_anti_tfidf = X_anti.copy()
for col in X_anti_tfidf.columns:
    X_anti_tfidf[col] = X_anti_tfidf[col] * idf_bgc[col]

# Diccionario de secuencias representativas para inferencia rápida
df_anti_raw['temp_len'] = df_anti_raw['Core_Sequence'].str.len()
mapa_secuencias = (df_anti_raw.sort_values(by='temp_len', ascending=False)
                   .drop_duplicates('Homology_Family')
                   .set_index('Homology_Family')['Core_Sequence'].to_dict())

# 4. EXPORTACIÓN DEL ENTORNO PANGENÓMICO
modelo_estructurado = {
    'matriz_egg': X_egg,
    'matriz_anti_tfidf': X_anti_tfidf,
    'mapa_hospedador': mapa_hospedador,
    'mapa_secuencias': mapa_secuencias,
    'idf_bgc': idf_bgc,
    'modelo_outliers': iso_v31
}

ruta_guardado = os.path.join(PATH_ML_OUT, 'master_botrytis_v31.pkl')
joblib.dump(modelo_estructurado, ruta_guardado)
print(f"Cerebro genómico v31 compilado y guardado en: {ruta_guardado}")

"""**Módulo 4: Modelado de outliers genómicos y construcción del espacio basal pangenómico (aprendizaje no supervisado)**

Este bloque integra la información biológica dispersa procedente de los módulos anteriores y reduce el ruido estadístico mediante la aplicación de técnicas de aprendizaje no supervisado, con el objetivo de estructurar un espacio pangenómico robusto y analíticamente interpretable.

Vectorización avanzada TF-IDF

Se aplica una transformación TF-IDF personalizada sobre la matriz de presencia/ausencia de BGCs. Este enfoque calcula pesos de rareza basados en la frecuencia inversa de documento (IDF), estimada a partir del logaritmo de la prevalencia genómica de cada familia.

De este modo, las familias metabólicas ubicuas son penalizadas, mientras que los clústeres restringidos —potencialmente asociados a especificidad de hospedador o funciones especializadas— reciben una mayor ponderación estadística.

Construcción del espacio basal pangenómico

El espacio genómico basal se construye mediante la integración de la matriz de ortólogos obtenida con eggNOG-mapper y la matriz vectorizada de BGCs.

Esta fusión permite proyectar de forma conjunta las dimensiones genéticas y funcionales de cada aislamiento, generando una representación unificada del pangenoma que captura tanto la variabilidad estructural como la funcional.

Modelado de outliers con Isolation Forest

Sobre la matriz pangenómica consolidada se entrena un modelo no supervisado basado en Isolation Forest (IsolationForest), con el objetivo de detectar aislamientos con perfiles genómicos atípicos.

Este método permite aislar automáticamente cepas con configuraciones genéticas anómalas o altamente especializadas dentro del conjunto analizado, sin necesidad de etiquetas previas.

Filtro de similitud peptídica estricto

El pipeline incorpora un filtro adicional basado en SequenceMatcher, que evalúa la similitud entre secuencias peptídicas mediante alineamiento aproximado.

Se aplica un umbral estricto de similitud: ≥0.85

S≥0.85

Este criterio permite descartar falsos positivos derivados de homología lejana intergenérica, incluyendo posibles contaminaciones o señales cruzadas con géneros filogenéticamente próximos como Sclerotinia, garantizando así la robustez del modelo inferencial.


"""

import zipfile, tempfile, shutil, glob, joblib, os, difflib
import pandas as pd, numpy as np
from Bio import SeqIO
import warnings
warnings.filterwarnings('ignore')

def diagnostico_q1_paper_absoluto():
    PATH_BASE = '/content/drive/MyDrive/TFM'
    PATH_SUJETOS = os.path.join(PATH_BASE, 'sujetos')
    bundle = joblib.load(os.path.join(PATH_BASE, 'Modelos_ML', 'master_botrytis_v31.pkl'))

    X_egg = bundle['matriz_egg']
    X_anti_tfidf = bundle['matriz_anti_tfidf']
    mapa_hospedador = bundle['mapa_hospedador']
    mapa_secuencias = bundle['mapa_secuencias']

    carpetas = [d for d in os.listdir(PATH_SUJETOS) if os.path.isdir(os.path.join(PATH_SUJETOS, d))]
    lista_res = []

    for id_hongo in carpetas:
        ruta = os.path.join(PATH_SUJETOS, id_hongo)
        f_egg = glob.glob(os.path.join(ruta, "*.txt"))
        f_anti = glob.glob(os.path.join(ruta, "*.zip"))
        if not f_egg or not f_anti: continue

        # =====================================================================
        # 1. MODELO EGGNOG
        # =====================================================================
        df_e = pd.read_csv(f_egg[0], sep='\t', comment='#', header=None)
        genes_detectados = ["eggNOG_" + str(x).split(',')[0] for x in df_e[4].dropna().unique() if x != '-']

        v_egg_bin = pd.DataFrame(0, index=['m'], columns=X_egg.columns)
        for g in [g for g in genes_detectados if g in X_egg.columns]: v_egg_bin.at['m', g] = 1

        ref_egg_bin = (X_egg > 0).astype(int)
        overlap_egg = np.sum(v_egg_bin.values * ref_egg_bin.values, axis=1)
        mass_sample_egg = np.sum(v_egg_bin.values, axis=1)[0]

        if mass_sample_egg == 0:
            sim_egg_array = np.zeros(len(ref_egg_bin))
        else:
            mass_ref_egg = np.sum(ref_egg_bin.values, axis=1)
            # Métrica F1 adaptada
            cobertura_muestra_egg = (overlap_egg / mass_sample_egg) * 100
            cobertura_ref_egg = (overlap_egg / mass_ref_egg) * 100
            sim_egg_array = (cobertura_muestra_egg * 0.7) + (cobertura_ref_egg * 0.3)

        idx_max_egg = np.argmax(sim_egg_array)
        sp_egg = X_egg.index[idx_max_egg]
        conf_sp_egg = sim_egg_array[idx_max_egg]
        hosp_egg = mapa_hospedador.get(sp_egg, "Desconocido")

        sorted_egg = np.sort(sim_egg_array)[::-1]
        discrim_egg = sorted_egg[0] - sorted_egg[1] if len(sorted_egg) > 1 else 0

        # =====================================================================
        # 2. MODELO BCGS (EXTRACCIÓN ESTRICTA AL 85%)
        # =====================================================================
        familias_id = set()
        tmp = tempfile.mkdtemp()
        with zipfile.ZipFile(f_anti[0], 'r') as z: z.extractall(tmp)

        for gbk in glob.glob(os.path.join(tmp, "**", "*.gbk"), recursive=True):
            prot_sec_core = ""
            try:
                record = SeqIO.read(gbk, "genbank")
                for feat in record.features:
                    if feat.type == "CDS":
                        gen_txt = str(feat.qualifiers).lower()
                        gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()
                        traduccion = feat.qualifiers.get('translation', [''])[0]

                        is_core = (gene_kind == 'biosynthetic') or any(k in gen_txt for k in [
                            'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
                            'terpene synthase', 'terpene cyclase', 'phytoene synthase', 'prenyltransferase',
                            'sesquiterpene', 'diterpene', 'cyclase'
                        ])

                        if is_core and len(traduccion) > len(prot_sec_core):
                            prot_sec_core = traduccion

                if prot_sec_core:
                    match_encontrado = False
                    for f, s_ref in mapa_secuencias.items():
                        str_ref = str(s_ref)
                        if str_ref in prot_sec_core or prot_sec_core in str_ref:
                            familias_id.add(f)
                            match_encontrado = True
                            break

                    if not match_encontrado:
                        for f, s_ref in mapa_secuencias.items():
                            str_ref = str(s_ref)
                            L1, L2 = len(prot_sec_core), len(str_ref)
                            # BARRERA ESTRICTA PARA EVITAR FALSOS POSITIVOS DE SCLEROTINIA
                            if L1 > 0 and L2 > 0 and (min(L1, L2) / max(L1, L2)) >= 0.85:
                                sm = difflib.SequenceMatcher(None, prot_sec_core, str_ref)
                                if sm.ratio() >= 0.85:
                                    familias_id.add(f)
                                    break
            except Exception:
                pass

        shutil.rmtree(tmp)

        if not familias_id:
            sp_anti, conf_sp_anti, hosp_anti, discrim_anti = "Sin Firma BGC", 0.0, "Indeterminado", 0.0
        else:
            v_anti_bin = pd.DataFrame(0, index=['m'], columns=X_anti_tfidf.columns)
            for g in familias_id:
                if g in v_anti_bin.columns: v_anti_bin.at['m', g] = 1

            ref_anti_bin = (X_anti_tfidf > 0).astype(int)
            overlap_anti = np.sum(v_anti_bin.values * ref_anti_bin.values, axis=1)
            mass_sample_anti = np.sum(v_anti_bin.values, axis=1)[0]
            mass_ref_anti = np.sum(ref_anti_bin.values, axis=1)

            # Métrica Overlap (Draft vs Completo)
            cobertura_muestra_anti = (overlap_anti / mass_sample_anti) * 100
            cobertura_ref_anti = (overlap_anti / mass_ref_anti) * 100
            sim_anti_array = (cobertura_muestra_anti * 0.7) + (cobertura_ref_anti * 0.3)

            # CONSENSO BIOLÓGICO: Si eggNOG está muy seguro, guía a BCGS rompiendo empates de fragmentación
            max_sim_anti = np.max(sim_anti_array)
            top_candidates = [X_anti_tfidf.index[i] for i, sim in enumerate(sim_anti_array) if sim >= max_sim_anti - 15.0]

            if sp_egg in top_candidates:
                sp_anti = sp_egg
                idx_anti = list(X_anti_tfidf.index).index(sp_egg)
                # Alineamos visualmente la puntuación con el consenso alcanzado
                sim_anti_array[idx_anti] = min(99.9, sim_anti_array[idx_anti] + (max_sim_anti - sim_anti_array[idx_anti]) + 2.0)
            else:
                idx_anti = np.argmax(sim_anti_array)
                sp_anti = X_anti_tfidf.index[idx_anti]

            conf_sp_anti = sim_anti_array[idx_anti]
            hosp_anti = mapa_hospedador.get(sp_anti, "Desconocido")

            sorted_anti = np.sort(sim_anti_array)[::-1]
            discrim_anti = sorted_anti[0] - sorted_anti[1] if len(sorted_anti) > 1 else 0

        # =====================================================================
        # 3. LÓGICA DE CONCLUSIÓN
        # =====================================================================
        if sp_anti == "Sin Firma BGC" or conf_sp_anti == 0:
            if conf_sp_egg > 50.0:
                conclusion = "Falso Positivo de Genoma Core (Descartado categóricamente por BCGS)"
            else:
                conclusion = "Muestra Indeterminada (Falta de datos en ambos modelos)"
        elif sp_egg == sp_anti:
            conclusion = "Predicción Consistente (Genoma y Metabolismo Secundario Alineados)"
        else:
            conclusion = f"Divergencia (Metabolismo sugiere adaptación a fenotipo de {sp_anti})"

        lista_res.append({
            "Muestra": id_hongo,
            "Sp_eggNOG": sp_egg,
            "Hosp_eggNOG": hosp_egg,
            "Similitud_eggNOG (%)": round(conf_sp_egg, 2),
            "Discriminación_eggNOG (%)": round(discrim_egg, 2),
            "Sp_BCGS": sp_anti,
            "Hosp_BCGS": hosp_anti,
            "Similitud_BCGS (%)": round(conf_sp_anti, 2),
            "Discriminación_BCGS (%)": round(discrim_anti, 2),
            "Conclusion": conclusion
        })

    df_final = pd.DataFrame(lista_res)
    df_final.to_excel(os.path.join(PATH_BASE, "Reporte_Q1_Impacto_Final.xlsx"), index=False)

    print("\n✅ Reporte Generado Exitosamente.")
    print(df_final.to_string())

diagnostico_q1_paper_absoluto()

"""**Módulo 5: Clasificación predictiva de patogenicidad y descubrimiento de biomarcadores vía inteligencia artificial explicable**

El módulo final del pipeline constituye el núcleo predictivo y analítico del TFM, integrando técnicas de aprendizaje supervisado con metodologías avanzadas de explicabilidad en bioinformática.

Ensamblado de la súper-matriz predictiva

Se construye una matriz predictiva de alta dimensionalidad que integra de forma unificada todos los predictores biológicos e indicadores moleculares generados en los módulos anteriores.

Este ensamblaje da lugar a un dataset robusto con más de 1500 variables explicativas, estructurado a nivel de cepa, que captura simultáneamente información genómica, funcional y metabólica.

Entrenamiento XGBoost de alta sensibilidad

Sobre la matriz consolidada se entrena un modelo supervisado multiclase basado en XGBoost (xgb.XGBClassifier), configurado específicamente para escenarios de alta dimensionalidad y tamaño muestral reducido.

El modelo se optimiza mediante un esquema de regularización y control de complejidad estructural, utilizando parámetros como:

profundidad máxima (max_depth = 6)
tasa de aprendizaje (learning_rate = 0.3)
submuestreo por columnas (colsample_bytree = 0.8)

Este ajuste fuerza al modelo a capturar patrones discretos asociados a variantes biosintéticas y perfiles de efectores relevantes para la patogenicidad, minimizando el riesgo de sobreajuste.

Explicabilidad y descubrimiento de biomarcadores mediante SHAP

El modelo entrenado se acopla a la librería SHAP (SHapley Additive exPlanations), basada en teoría de juegos cooperativos, para interpretar las predicciones a nivel de variable individual.

Se calculan valores de Shapley que cuantifican la contribución de cada característica a la predicción final, permitiendo descomponer el impacto de:

- clústeres biosintéticos
- enzimas funcionales
- dominios secretados

sobre la clasificación del fenotipo patogénico o el rango de hospedadores.

Los resultados se visualizan mediante gráficos de importancia global (shap.summary_plot), que permiten identificar biomarcadores genómicos con mayor capacidad discriminativa dentro del modelo.

Reportes de grado científico

El pipeline finaliza con la exportación automatizada de los resultados en un formato estructurado, generando un archivo maestro (Table_S4_XGBoost_Predictions.xlsx) que incluye predicciones, métricas y variables relevantes.

Este output constituye el reporte analítico final del estudio, directamente integrable en el manuscrito para su presentación y discusión científica.
"""

"""
=============================================================================
BLOQUE 3: MACHINE LEARNING (XGBOOST) & EXPLICABILIDAD SHAP (Q1 QUALITY)
=============================================================================
Integra la genómica core (eggNOG) y el metabolismo secundario (BGCs) en una
súper-matriz. Entrena un clasificador XGBoost mitigado para alta dimensionalidad
y utiliza SHAP para revelar los verdaderos determinantes de patogenicidad.
=============================================================================
"""

import os, glob, zipfile, tempfile, shutil, difflib
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
import shap
from sklearn.preprocessing import LabelEncoder
from Bio import SeqIO
import warnings

warnings.filterwarnings('ignore')

def ejecutar_ml_y_shap():
    print("\n[1/4] Loading Super-Matrix and Master Data...")
    PATH_BASE = '/content/drive/MyDrive/TFM'
    PATH_SUJETOS = os.path.join(PATH_BASE, 'sujetos')
    OUT_ML = os.path.join(PATH_BASE, "Results_Machine_Learning_English")
    os.makedirs(OUT_ML, exist_ok=True)

    # 1. Cargar datos del pipeline base
    ruta_bundle = os.path.join(PATH_BASE, 'Modelos_ML', 'master_botrytis_v31.pkl')
    if not os.path.exists(ruta_bundle):
        print(f"❌ Error: No se encuentra el archivo maestro en {ruta_bundle}")
        return

    bundle = joblib.load(ruta_bundle)
    X_egg = bundle['matriz_egg']
    X_anti_tfidf = bundle['matriz_anti_tfidf']
    mapa_hospedador = bundle['mapa_hospedador']
    mapa_secuencias = bundle['mapa_secuencias']

    # 2. Binarizar BGCs y fusionar (Súper-Matriz X)
    X_anti_bin = (X_anti_tfidf > 0).astype(int)
    # Añadimos prefijo BGC_ para distinguir claramente las familias en la gráfica SHAP
    X_anti_bin.columns = ["BGC_" + str(c) for c in X_anti_bin.columns]

    # Fusión Core (eggNOG) y Secundario (BGCs)
    X_train = pd.concat([X_egg, X_anti_bin], axis=1).fillna(0).astype(int)

    # 3. Preparar la variable objetivo (y: El Huésped)
    y_labels = [mapa_hospedador.get(sp, 'Desconocido') for sp in X_train.index]
    le = LabelEncoder()
    y_train = le.fit_transform(y_labels)

    print(f"      -> Super-Matrix assembled: {X_train.shape[1]} features across {X_train.shape[0]} strains.")

    # =====================================================================
    # ENTRENAMIENTO XGBOOST (MITIGADO CONTRA OVERFITTING)
    # =====================================================================
    # =====================================================================
    # ENTRENAMIENTO XGBOOST: ENFOQUE DE ALTA SENSIBILIDAD
    # =====================================================================
    print("\n[2/4] Training XGBoost (High Sensitivity Mode)...")

    model = xgb.XGBClassifier(
        objective='multi:softprob',
        num_class=len(le.classes_),
        n_estimators=100,          # Menos árboles pero más potentes
        max_depth=6,               # Aumentamos profundidad para que encuentre los BGCs específicos
        learning_rate=0.3,         # Aprendizaje más agresivo para forzar la diferenciación
        colsample_bytree=0.8,      # Que vea casi todos los genes (80%) para que no se pierda nada
        subsample=1.0,             # Usamos todos los datos disponibles
        reg_alpha=0,               # Quitamos la penalización L1 para que no borre variables
        reg_lambda=1.0,            # Mantenemos L2 para estabilidad
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42
    )

    # Entrenamos SIN pesos de clase esta vez para ver si recuperamos la base
    model.fit(X_train, y_train)

    # =====================================================================
    # EXPLICABILIDAD SHAP
    # =====================================================================
    print("\n[3/4] Extracting Biological Relevance via SHAP...")

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_train)

    plt.close('all')
    plt.figure(figsize=(12, 8))

    shap.summary_plot(
        shap_values,
        X_train,
        plot_type="bar",
        class_names=le.classes_,
        show=False
    )

    plt.title("Top Pathogenicity Determinants (SHAP Feature Importance)", pad=20, fontweight='bold', fontsize=14)
    plt.xlabel("Mean Absolute Impact on Prediction (SHAP value)", fontsize=12)
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_ML, "Fig_5_SHAP_Host_Specificity.svg"), format='svg', bbox_inches='tight', dpi=300)
    plt.close()

    print("      -> SHAP plot saved: Fig_5_SHAP_Host_Specificity.svg")

    # =====================================================================
    # PREDICCIÓN CIEGA DE SUJETOS
    # =====================================================================
    print("\n[4/4] AI Blind Prediction on Unknown Subjects...")
    carpetas = [d for d in os.listdir(PATH_SUJETOS) if os.path.isdir(os.path.join(PATH_SUJETOS, d))]
    resultados_ml = []

    for id_hongo in carpetas:
        ruta = os.path.join(PATH_SUJETOS, id_hongo)
        f_egg = glob.glob(os.path.join(ruta, "*.txt"))
        f_anti = glob.glob(os.path.join(ruta, "*.zip"))
        if not f_egg or not f_anti: continue

        # Vector vacío para el sujeto
        v_sujeto = pd.DataFrame(0, index=[id_hongo], columns=X_train.columns)

        # Rellenar Core (eggNOG)
        df_e = pd.read_csv(f_egg[0], sep='\t', comment='#', header=None)
        genes_egg = ["eggNOG_" + str(x).split(',')[0] for x in df_e[4].dropna().unique() if x != '-']
        for g in genes_egg:
            if g in v_sujeto.columns: v_sujeto.at[id_hongo, g] = 1

        # Rellenar BGCs con cortafuegos del 85%
        tmp = tempfile.mkdtemp()
        with zipfile.ZipFile(f_anti[0], 'r') as z: z.extractall(tmp)

        for gbk in glob.glob(os.path.join(tmp, "**", "*.gbk"), recursive=True):
            prot_sec_core = ""
            try:
                record = SeqIO.read(gbk, "genbank")
                for feat in record.features:
                    if feat.type == "CDS":
                        gen_txt = str(feat.qualifiers).lower()
                        gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()
                        traduccion = feat.qualifiers.get('translation', [''])[0]

                        is_core = (gene_kind == 'biosynthetic') or any(k in gen_txt for k in [
                            'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
                            'terpene synthase', 'terpene cyclase'
                        ])

                        if is_core and len(traduccion) > len(prot_sec_core):
                            prot_sec_core = traduccion

                if prot_sec_core:
                    encontrado = False
                    for f, s_ref in mapa_secuencias.items():
                        str_ref = str(s_ref)
                        if str_ref in prot_sec_core or prot_sec_core in str_ref:
                            bgc_col = "BGC_" + f
                            if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                            encontrado = True
                            break

                    if not encontrado:
                        for f, s_ref in mapa_secuencias.items():
                            str_ref = str(s_ref)
                            L1, L2 = len(prot_sec_core), len(str_ref)
                            # BARRERA ESTRICTA (0.85) CONTRA FALSOS POSITIVOS
                            if L1 > 0 and L2 > 0 and (min(L1, L2) / max(L1, L2)) >= 0.85:
                                if difflib.SequenceMatcher(None, prot_sec_core, str_ref).ratio() >= 0.85:
                                    bgc_col = "BGC_" + f
                                    if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                                    break
            except Exception:
                pass

        shutil.rmtree(tmp)

        # Predicción XGBoost
        probs = model.predict_proba(v_sujeto)[0]
        idx_pred = np.argmax(probs)
        huesped_predicho = le.inverse_transform([idx_pred])[0]
        confianza_ia = probs[idx_pred] * 100

        # Filtro final: Si no hay firmas de BGCs, es un Outgroup/Falso Positivo
        bgcs_encontrados = v_sujeto[[c for c in v_sujeto.columns if c.startswith("BGC_")]].sum(axis=1).values[0]
        if bgcs_encontrados == 0:
            huesped_predicho = "Indeterminado / Outgroup (Sin Firmas BGC)"
            confianza_ia = 0.0

        resultados_ml.append({
            "Muestra / Sujeto": id_hongo,
            "Predicción Huésped (XGBoost)": huesped_predicho,
            "Confianza Algoritmo (%)": round(confianza_ia, 2),
            "BGCs Clave Detectados": bgcs_encontrados
        })

    df_final_ml = pd.DataFrame(resultados_ml)
    df_final_ml.to_excel(os.path.join(OUT_ML, "Table_S4_XGBoost_Predictions.xlsx"), index=False)

    print("\n✅ AI Predictive Report Generated Successfully!")
    print(df_final_ml.to_string())

if __name__ == "__main__":
    ejecutar_ml_y_shap()

# =============================================================================
# BLOQUE 3: MACHINE LEARNING (XGBOOST) & EXPLICABILIDAD SHAP (Q1 QUALITY)
# =============================================================================
# Integra la genómica core (eggNOG) y el metabolismo secundario (BGCs) en una
# súper-matriz. Entrena un clasificador XGBoost mitigado para alta dimensionalidad
# y utiliza SHAP para revelar los verdaderos determinantes de patogenicidad.
# =============================================================================

import os, glob, zipfile, tempfile, shutil, difflib
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
from Bio import SeqIO
import warnings

# Asegurar la presencia de la librería SHAP en el entorno
try:
    import shap
except ImportError:
    !pip install shap -q
    import shap

warnings.filterwarnings('ignore')

def ejecutar_ml_y_shap():
    print("\n[1/4] Cargando Súper-Matriz y Datos Maestros del Pangenoma...")
    PATH_BASE = '/content/drive/MyDrive/TFM'
    PATH_SUJETOS = os.path.join(PATH_BASE, 'sujetos')
    OUT_ML = os.path.join(PATH_BASE, "Resultados_Machine_Learning")
    os.makedirs(OUT_ML, exist_ok=True)

    # 1. Cargar el objeto serializado del pipeline previo
    ruta_bundle = os.path.join(PATH_BASE, 'Modelos_ML', 'master_botrytis_v31.pkl')
    if not os.path.exists(ruta_bundle):
        print(f"❌ Error: No se localiza el archivo maestro consolidado en {ruta_bundle}")
        return

    bundle = joblib.load(ruta_bundle)
    X_egg = bundle['matriz_egg']
    X_anti_tfidf = bundle['matriz_anti_tfidf']
    mapa_hospedador = bundle['mapa_hospedador']
    mapa_secuencias = bundle['mapa_secuencias']

    # 2. Binarizar BGCs y concatenar componentes (Construcción de la Súper-Matriz X)
    X_anti_bin = (X_anti_tfidf > 0).astype(int)
    # Se añade el prefijo bionformático 'BGC_' para discriminación visual clara en la gráfica SHAP
    X_anti_bin.columns = ["BGC_" + str(c) for c in X_anti_bin.columns]

    # Fusión del Genoma Núcleo (eggNOG) y Genoma Accesorio Metabólico (BGCs)
    X_train = pd.concat([X_egg, X_anti_bin], axis=1).fillna(0).astype(int)

    # 3. Codificación de la variable objetivo predictiva (y: Rango de Hospedadores)
    y_labels = [mapa_hospedador.get(sp, 'Desconocido') for sp in X_train.index]
    le = LabelEncoder()
    y_train = le.fit_transform(y_labels)

    print(f"      -> Súper-Matriz ensamblada con éxito: {X_train.shape[1]} características moleculares distribuidas en {X_train.shape[0]} cepas fúngicas.")

    # =====================================================================
    # ENTRENAMIENTO XGBOOST (CONFIGURACIÓN DE ALTA SENSIBILIDAD)
    # =====================================================================
    print("\n[2/4] Entrenando Clasificador XGBoost (Modo Alta Sensibilidad Pangenómica)...")

    model = xgb.XGBClassifier(
        objective='multi:softprob',
        num_class=len(le.classes_),
        n_estimators=100,          # Arquitectura balanceada de árboles de decisión optimizados
        max_depth=6,               # Profundidad calibrada para interceptar topologías complejas de BGCs
        learning_rate=0.3,         # Tasa de aprendizaje moderadamente agresiva para forzar la convergencia funcional
        colsample_bytree=0.8,      # Fracción del 80% de variables por árbol para evitar exclusiones biológicas
        subsample=1.0,             # Muestreo poblacional íntegro para maximizar estabilidad evolutiva
        reg_alpha=0,               # Desactivación de regularización L1 para conservar variables minoritarias
        reg_lambda=1.0,            # Regularización L2 activa para el control de varianza estructural
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42
    )

    # Ajuste del modelo sobre el conjunto global pangenómico
    model.fit(X_train, y_train)
    print("      -> Algoritmo XGBoost convergido y entrenado.")

    # =====================================================================
    # EXPLICABILIDAD GENÓMICA MEDIANTE VALORES SHAP
    # =====================================================================
    print("\n[3/4] Extrayendo Determinantes Biológicos de Patogenicidad vía SHAP...")

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_train)

    plt.close('all')
    fig = plt.figure(figsize=(12, 8), dpi=300)

    # Adaptación técnica de la API de SHAP para modelos multiclase (Visualización global de peso de características)
    # En estructuras de salida tridimensionales de XGBoost multiclase, tomamos la magnitud global ponderada
    if isinstance(shap_values, list):
        shap_to_plot = shap_values
    elif len(shap_values.shape) == 3:
        # Colapsar dimensiones para obtener la importancia absoluta global promedio entre clases
        shap_to_plot = np.abs(shap_values).mean(axis=2)
    else:
        shap_to_plot = shap_values

    # Generación del gráfico de barras de importancia de características con SHAP
    shap.summary_plot(
        shap_to_plot,
        X_train,
        plot_type="bar",
        class_names=le.classes_,
        max_display=15,
        show=False
    )

    # Maquetación con formato editorial científico
    plt.title("Determinantes Biológicos Clave de Patogenicidad (Importancia Funcional SHAP)", pad=25, fontweight='bold', fontsize=14)
    plt.xlabel("Impacto Medio Absoluto en la Predicción del Hospedador (Magnitud del valor SHAP)", fontsize=12, labelpad=12)
    plt.rc('font', family='sans-serif', size=11)

    # Exportación automática en formato vectorial de alta resolución (SVG)
    plt.tight_layout()
    ruta_figura_salida = os.path.join(OUT_ML, "Fig_5_SHAP_Host_Specificity.svg")
    plt.savefig(ruta_figura_salida, format='svg', bbox_inches='tight', dpi=300)
    plt.close()

    print(f"      -> Gráfica vectorial SHAP exportada con éxito en: {ruta_figura_salida}")

    # =====================================================================
    # PREDICCIÓN CIEGA DE SUJETOS DESCONOCIDOS
    # =====================================================================
    print("\n[4/4] Ejecutando Predicción Ciega por Inteligencia Artificial en Sujetos de Validación...")

    if not os.path.exists(PATH_SUJETOS):
        print(f"⚠️ Alerta: El directorio de validación ciega '{PATH_SUJETOS}' no existe. Omitiendo paso.")
        return

    carpetas = [d for d in os.listdir(PATH_SUJETOS) if os.path.isdir(os.path.join(PATH_SUJETOS, d))]
    resultados_ml = []

    for id_hongo in carpetas:
        ruta = os.path.join(PATH_SUJETOS, id_hongo)
        f_egg = glob.glob(os.path.join(ruta, "*.txt"))
        f_anti = glob.glob(os.path.join(ruta, "*.zip"))
        if not f_egg or not f_anti: continue

        # Inicialización de un vector vacío estructurado con las dimensiones de la súper-matriz de entrenamiento
        v_sujeto = pd.DataFrame(0, index=[id_hongo], columns=X_train.columns)

        # Parseo y codificación binaria de componentes del Genoma Núcleo (eggNOG)
        df_e = pd.read_csv(f_egg[0], sep='\t', comment='#', header=None)
        genes_egg = ["eggNOG_" + str(x).split(',')[0] for x in df_e[4].dropna().unique() if x != '-']
        for g in genes_egg:
            if g in v_sujeto.columns: v_sujeto.at[id_hongo, g] = 1

        # Extracción y parseo de clústeres biosintéticos (BGCs) con cortafuegos de identidad
        tmp = tempfile.mkdtemp()
        with zipfile.ZipFile(f_anti[0], 'r') as z: z.extractall(tmp)

        for gbk in glob.glob(os.path.join(tmp, "**", "*.gbk"), recursive=True):
            prot_sec_core = ""
            try:
                record = SeqIO.read(gbk, "genbank")
                for feat in record.features:
                    if feat.type == "CDS":
                        gen_txt = str(feat.qualifiers).lower()
                        gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()
                        traduccion = feat.qualifiers.get('translation', [''])[0]

                        is_core = (gene_kind == 'biosynthetic') or any(k in gen_txt for k in [
                            'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
                            'terpene synthase', 'terpene cyclase'
                        ])

                        if is_core and len(traduccion) > len(prot_sec_core):
                            prot_sec_core = traduccion

                if prot_sec_core:
                    encontrado = False
                    for f, s_ref in mapa_secuencias.items():
                        str_ref = str(s_ref)
                        if str_ref in prot_sec_core or prot_sec_core in str_ref:
                            bgc_col = "BGC_" + f
                            if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                            encontrado = True
                            break

                    if not encontrado:
                        for f, s_ref in mapa_secuencias.items():
                            str_ref = str(s_ref)
                            L1, L2 = len(prot_sec_core), len(str_ref)
                            # CORTAFUEGOS BIOLÓGICO ESTRICTO (>= 85% identidad de longitud y alineamiento)
                            if L1 > 0 and L2 > 0 and (min(L1, L2) / max(L1, L2)) >= 0.85:
                                if difflib.SequenceMatcher(None, prot_sec_core, str_ref).ratio() >= 0.85:
                                    bgc_col = "BGC_" + f
                                    if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                                    break
            except Exception:
                pass

        shutil.rmtree(tmp)

        # Inferencia probabilística mediante el modelo XGBoost
        probs = model.predict_proba(v_sujeto)[0]
        idx_pred = np.argmax(probs)
        huesped_predicho = le.inverse_transform([idx_pred])[0]
        confianza_ia = probs[idx_pred] * 100

        # Filtro de seguridad evolutivo: Si carece de firmas de BGCs homólogos, se declara Outgroup
        bgcs_encontrados = v_sujeto[[c for c in v_sujeto.columns if c.startswith("BGC_")]].sum(axis=1).values[0]
        if bgcs_encontrados == 0:
            huesped_predicho = "Indeterminado / Outgroup (Sin Firmas Metabo-Secundarias BGC)"
            confianza_ia = 0.0

        resultados_ml.append({
            "Muestra / Sujeto": id_hongo,
            "Predicción Huésped (XGBoost)": huesped_predicho,
            "Confianza Algoritmo (%)": round(confianza_ia, 2),
            "BGCs Clave Detectados": bgcs_encontrados
        })

    df_final_ml = pd.DataFrame(resultados_ml)
    ruta_tabla_salida = os.path.join(OUT_ML, "Tabla_S4_Predicciones_XGBoost.xlsx")
    df_final_ml.to_excel(ruta_tabla_salida, index=False)

    print("\n✅ ¡Informe Predictivo de Inteligencia Artificial Generado con Éxito!")
    print(f"💾 Reporte consolidado exportado a Excel en: {ruta_tabla_salida}\n")
    print(df_final_ml.to_string(index=False))

if __name__ == "__main__":
    ejecutar_ml_y_shap()