# -*- coding: utf-8 -*-
"""Códigos_TFM_Módulo_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QTWTwO1kvzWZcpL45NskVWGkR1GJhBe

**Módulo 2: Pangenómica de BGCs, Análisis de Sintenia Comparativa y Visualización de Arquitecturas Singulares**

Este bloque procesa el espacio genómico secundario bajo un enfoque pangenómico para evaluar la conservación molecular e interconectar variantes estructurales entre cepas.

Clustering Homólogo por CD-HIT: Extrae las secuencias peptídicas de los genes biosintéticos core de mayor longitud e implementa el algoritmo de agrupamiento ultrarrápido CD-HIT (parámetros críticos: -c 0.7 -n 4), lo que permite clasificar los BGCs en "Familias de Homología" inter-cepa.

Modelado del Espacio Pangenómico: Construye matrices globales de presencia/ausencia para cada categoría metabólica (NRPS, PKS, Terpenos, etc.) y evalúa la prevalencia de cada familia, catalogándola en compartimentos pangenómicos definidos (Strict Core, Accessory o Specific Singleton).

Análisis Sinténico Dinámico con Clinker: Para aquellos grupos categorizados como estructuralmente conservados en toda la población genómica (Strict Core), el sistema automatiza la ejecución de Clinker con un umbral de identidad estricto (-i 0.4), generando diagramas sinténicos dinámicos e interactivos en HTML para el estudio de reordenamientos cromosómicos.

Visualización de Arquitecturas Exclusivas: Para variantes metabólicas únicas de un solo aislamiento (Specific Singletons), implementa el renderizado vectorial automatizado en formato SVG mediante DNA Features Viewer, mapeando con código de colores la orientación funcional exacta del locus biosintético.

Intersección Multidimensional: Utiliza la librería UpSetPlot para graficar la intersección combinatoria de las familias homólogas, superando las limitaciones de los diagramas de Venn tradicionales para analizar el solapamiento molecular masivo.
"""

import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

try:
    import openpyxl
    from upsetplot import plot as upset_plot
except ImportError:
    os.system("pip install openpyxl upsetplot")
    import openpyxl
    from upsetplot import plot as upset_plot

warnings.filterwarnings('ignore')

# -----------------------------------------------------------------------------
# 1. PATHS AND ENVIRONMENT SETTINGS
# -----------------------------------------------------------------------------
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    BASE_PATH = "/content/drive/MyDrive/TFM"
except ImportError:
    BASE_PATH = "./TFM"

DIR_DIAMOND = os.path.join(BASE_PATH, "archivos_diamond")
DIR_EGGNOG = os.path.join(BASE_PATH, "archivos_eggnogg")

OUT_FIGS = os.path.join(BASE_PATH, "Results_Publication_SVG_English")
OUT_TABS = os.path.join(BASE_PATH, "Results_Publication_Excel_English")
OUT_ML = os.path.join(BASE_PATH, "Results_Machine_Learning_English")

for d in [OUT_FIGS, OUT_TABS, OUT_ML]:
    os.makedirs(d, exist_ok=True)

UMBRAL_ID = 70.0

# Official COG Dictionary mapped exactly for both Heatmap and UpSet Plot
COG_DICT = {
    'J': 'Translation & Ribosomes', 'A': 'RNA processing', 'K': 'Transcription',
    'L': 'Replication & Repair', 'B': 'Chromatin structure', 'D': 'Cell cycle control',
    'V': 'Defense mechanisms', 'T': 'Signal transduction', 'M': 'Cell wall membrane',
    'N': 'Cell motility', 'Z': 'Cytoskeleton', 'W': 'Extracellular structures',
    'O': 'Posttranslational mod', 'C': 'Energy production', 'G': 'Carbohydrate metabolism',
    'E': 'Amino acid metabolism', 'F': 'Nucleotide metabolism', 'H': 'Coenzyme metabolism',
    'I': 'Lipid metabolism', 'P': 'Inorganic ion metabolism', 'Q': 'Secondary metabolites',
    'R': 'General function prediction', 'S': 'Function unknown'
}

EC_CLASSES = {
    '1': '1. Oxidoreductases', '2': '2. Transferases', '3': '3. Hydrolases',
    '4': '4. Lyases', '5': '5. Isomerases', '6': '6. Ligases', '7': '7. Translocases'
}

# -----------------------------------------------------------------------------
# BLOCK 1: DIAMOND PROCESSING (SECRETOME EVOLUTIONARY BINS)
# -----------------------------------------------------------------------------
def procesar_diamond():
    print("\n[1/4] Processing Secretome Evolutionary Architecture (DIAMOND)...")
    archivos = glob.glob(os.path.join(DIR_DIAMOND, "*.txt")) + glob.glob(os.path.join(DIR_DIAMOND, "*.tsv"))
    if not archivos: return pd.DataFrame()

    lista_raw = []
    lista_stats = []

    for archivo in archivos:
        cepa = os.path.basename(archivo).split('.')[0].split('_')[0]
        try:
            df = pd.read_csv(archivo, sep='\t')
            df = df.iloc[:, :5]
            df.columns = ['qseqid', 'sseqid', 'evalue', 'bitscore', 'pident']
            df['pident'] = pd.to_numeric(df['pident'], errors='coerce')
            df['evalue'] = pd.to_numeric(df['evalue'], errors='coerce')
            df = df.dropna(subset=['pident', 'evalue'])

            df_filt = df[(df['evalue'] < 1e-10) & (df['pident'] >= UMBRAL_ID)].copy()
            df_filt['Strain'] = cepa

            bins = [70, 80, 90, 100.1]
            labels = ['Divergent (70-80%)', 'Conserved (80-90%)', 'High Identity (>90%)']
            df_filt['Evolutionary_Range'] = pd.cut(df_filt['pident'], bins=bins, labels=labels, right=False)

            lista_raw.append(df_filt)
            lista_stats.append({
                'Strain': cepa, 'Homologues (>=70%)': len(df_filt),
                'Mean Identity (%)': round(df_filt['pident'].mean(), 2)
            })
        except Exception as e:
            print(f"  ❌ Error in DIAMOND {cepa}: {e}")

    df_maestro = pd.concat(lista_raw)
    pd.DataFrame(lista_stats).to_excel(os.path.join(OUT_TABS, "Table_1_DIAMOND_Stats.xlsx"), index=False)

    # Fig 1A: Stacked Bar Chart
    plt.close('all')
    sns.set_theme(style="ticks", context="paper", font_scale=1.2)
    prop = df_maestro.groupby(['Strain', 'Evolutionary_Range']).size().unstack().fillna(0)
    prop_pct = prop.div(prop.sum(axis=1), axis=0) * 100

    ax = prop_pct.plot(kind='bar', stacked=True, figsize=(8, 6), color=['#e76f51', '#f4a261', '#2a9d8f'], width=0.6)
    plt.title('Evolutionary Profile of the Secretome (Fig 1A)', pad=15, fontweight='bold')
    plt.ylabel('Secretome Proportion (%)', fontweight='bold')
    plt.xlabel('Strain', fontweight='bold')
    plt.xticks(rotation=0)
    plt.legend(title='Conservation Range', bbox_to_anchor=(1.05, 1), loc='upper left', frameon=False)
    sns.despine()
    plt.savefig(os.path.join(OUT_FIGS, "Fig_1A_Secretome_Evolutionary_Ranges.svg"), format='svg', bbox_inches='tight')
    plt.close()

    # Fig 1B: UpSet Plot (CORREGIDO)
    matriz_dianas = pd.crosstab(df_maestro['sseqid'], df_maestro['Strain'])
    matriz_dianas_bool = (matriz_dianas > 0).astype(bool)

    upset_data = matriz_dianas_bool.groupby(list(matriz_dianas_bool.columns)).size()

    # Renderizado seguro para UpSetPlot
    fig = plt.figure(figsize=(12, 8))
    upset_plot(upset_data, sort_by='cardinality', show_counts=True, fig=fig)
    plt.suptitle('Intersection of Secreted Homologous Targets (Fig 1B)', fontweight='bold', fontsize=14, y=1.05)
    plt.savefig(os.path.join(OUT_FIGS, "Fig_1B_Secretome_Targets_UpSet.svg"), format='svg', bbox_inches='tight')
    plt.close(fig)

    return df_maestro

# -----------------------------------------------------------------------------
# BLOCK 2: EGGNOG PROCESSING (COG, EC, OGs for ML)
# -----------------------------------------------------------------------------
def procesar_eggnog():
    print("\n[2/4] Processing Functional Profiling (eggNOG)...")
    archivos = glob.glob(os.path.join(DIR_EGGNOG, "*.txt")) + glob.glob(os.path.join(DIR_EGGNOG, "*.annotations*"))
    if not archivos: return pd.DataFrame(), pd.DataFrame()

    lista_cogs, lista_ecs, lista_ogs_ml, lista_raw = [], [], [], []

    for archivo in archivos:
        cepa = os.path.basename(archivo).split('.')[0].split('_')[0]
        try:
            df = pd.read_csv(archivo, sep='\t', comment='#', header=None, low_memory=False)
            df.columns = ['query', 'seed', 'evalue', 'score', 'OGs', 'tax', 'COG_cat', 'desc', 'name', 'GO', 'EC', 'KO', 'Path', 'Mod', 'React', 'Rclass', 'BRITE', 'TC', 'CAZy', 'BiGG', 'PFAMs'][:len(df.columns)]
            df['Strain'] = cepa
            lista_raw.append(df)

            # Extract COG and OG for Orthology Integration (CORREGIDO)
            if 'COG_cat' in df.columns and 'OGs' in df.columns:
                for _, row in df[['query', 'COG_cat', 'OGs']].dropna().iterrows():
                    # Extraer el Grupo Ortólogo principal para poder encontrar intersecciones inter-cepa
                    og_principal = str(row['OGs']).split(',')[0]
                    for letra in str(row['COG_cat']):
                        if letra in COG_DICT:
                            lista_cogs.append({
                                'Strain': cepa,
                                'COG_Category': COG_DICT[letra],
                                'Code': letra,
                                'Query_ID': row['query'],
                                'OG': og_principal # Usaremos esto para el UpSet Plot
                            })

            # Extract EC
            if 'EC' in df.columns:
                for _, row in df[['query', 'EC']].dropna().iterrows():
                    for ec in str(row['EC']).split(','):
                        ec_clean = ec.strip()
                        ec_main = ec_clean.split('.')[0]
                        if ec_main in EC_CLASSES:
                            lista_ecs.append({'Strain': cepa, 'EC_Number': ec_clean, 'EC_Class': EC_CLASSES[ec_main]})

            if 'OGs' in df.columns:
                ogs = df[['query', 'OGs']].dropna()
                ogs = ogs[ogs['OGs'] != '-']
                ogs['Strain'] = cepa
                lista_ogs_ml.append(ogs)

        except Exception as e:
            print(f"  ❌ Error in eggNOG {cepa}: {e}")

    df_eggnog_completo = pd.concat(lista_raw)

    # --- COG VISUALIZATIONS ---
    df_cogs = pd.DataFrame(lista_cogs)
    if not df_cogs.empty:
        df_cogs_clean = df_cogs[~df_cogs['Code'].isin(['S', 'R'])]

        # Fig 2A: Heatmap COG
        plt.close('all')
        matriz_cog = pd.crosstab(df_cogs_clean['COG_Category'], df_cogs_clean['Strain'])
        plt.figure(figsize=(10, 8))
        sns.heatmap(matriz_cog, cmap="Blues", annot=True, fmt="d", linewidths=.5)
        plt.title('Biological COG Categories Distribution (Fig 2A)', pad=15, fontweight='bold')
        plt.ylabel('COG Category', fontweight='bold')
        plt.yticks(rotation=0)
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2A_COG_Heatmap.svg"), format='svg', bbox_inches='tight')
        plt.close()

        # Fig 2B: UPSET PLOTS POR CADA CATEGORIA COG (CORREGIDO)
        print("      Generating specific UpSet plots for each COG category...")
        for cat in df_cogs_clean['COG_Category'].unique():
            df_cat = df_cogs_clean[df_cogs_clean['COG_Category'] == cat]
            # Usar 'OG' en lugar de 'Query_ID' permite encontrar las dianas compartidas
            matriz_upset = pd.crosstab(df_cat['OG'], df_cat['Strain'])
            matriz_bool = (matriz_upset > 0).astype(bool)

            if len(matriz_bool.columns) > 1:
                try:
                    upset_data_cog = matriz_bool.groupby(list(matriz_bool.columns)).size()
                    fig = plt.figure(figsize=(10, 6))
                    upset_plot(upset_data_cog, sort_by='cardinality', show_counts=True, fig=fig)
                    plt.suptitle(f'Ortholog Intersection: {cat}', fontweight='bold', fontsize=12, y=1.05)
                    cat_safe = cat.replace('/', '_').replace(' ', '_').replace('(', '').replace(')', '').replace('&', 'and')
                    plt.savefig(os.path.join(OUT_FIGS, f"Fig_2B_UpSet_COG_{cat_safe}.svg"), format='svg', bbox_inches='tight')
                    plt.close(fig)
                except Exception as e:
                    pass

    # --- ENZYME (EC) VISUALIZATIONS ---
    df_ecs = pd.DataFrame(lista_ecs)
    if not df_ecs.empty:
        # Fig 2C: UpSet Plot EC Numbers (Aplicando renderizado seguro)
        matriz_ec = pd.crosstab(df_ecs['EC_Number'], df_ecs['Strain'])
        matriz_ec_bool = (matriz_ec > 0).astype(bool)
        upset_data_ec = matriz_ec_bool.groupby(list(matriz_ec_bool.columns)).size()

        fig3 = plt.figure(figsize=(12, 8))
        upset_plot(upset_data_ec, sort_by='cardinality', show_counts=True, fig=fig3)
        plt.suptitle('Enzymatic Repertoire Intersection (Fig 2C)', fontweight='bold', fontsize=14, y=1.05)
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2C_Enzymes_UpSet.svg"), format='svg', bbox_inches='tight')
        plt.close(fig3)

        # Fig 2D: EC Classes Bar Chart
        plt.close('all')
        matriz_ec_classes = pd.crosstab(df_ecs['EC_Class'], df_ecs['Strain'])
        matriz_ec_classes.plot(kind='bar', figsize=(10, 6), colormap='viridis', width=0.7)
        plt.title('Distribution of Main Enzyme Classes (Fig 2D)', pad=15, fontweight='bold')
        plt.ylabel('Number of Enzymes', fontweight='bold')
        plt.xlabel('Enzyme Class', fontweight='bold')
        plt.xticks(rotation=45, ha='right')
        sns.despine()
        plt.savefig(os.path.join(OUT_FIGS, "Fig_2D_EC_Classes.svg"), format='svg', bbox_inches='tight')
        plt.close()

    if not df_cogs.empty: pd.crosstab(df_cogs['COG_Category'], df_cogs['Strain']).to_excel(os.path.join(OUT_TABS, "Table_S2A_COG_Full.xlsx"))
    if not df_ecs.empty: matriz_ec.to_excel(os.path.join(OUT_TABS, "Table_S2B_EC_Matrix.xlsx"))

    # ML Predictors
    df_ml_raw = pd.concat(lista_ogs_ml)
    df_ml_raw['Predictor_ID'] = "eggNOG_" + df_ml_raw['OGs'].apply(lambda x: str(x).split(',')[0])
    matriz_pa_eggnog = pd.crosstab(df_ml_raw['Predictor_ID'], df_ml_raw['Strain'])
    matriz_pa_eggnog = (matriz_pa_eggnog > 0).astype(int)

    return df_eggnog_completo, matriz_pa_eggnog

# -----------------------------------------------------------------------------
# BLOCK 3: SECRETOME ECOLOGICAL FRACTIONATION
# -----------------------------------------------------------------------------
def clasificar_secretoma(row):
    cazy = str(row.get('CAZy', '-'))
    pfam = str(row.get('PFAMs', '-')).lower()
    desc = str(row.get('desc', '-')).lower()
    if cazy != '-': return 'CAZymes (PCW Degradation)'
    elif any(x in pfam or x in desc for x in ['peptidase', 'protease']): return 'Proteases / Peptidases'
    elif any(x in pfam or x in desc for x in ['lipase', 'esterase']): return 'Lipases / Esterases'
    elif 'oxidoreductase' in pfam or 'oxidoreductase' in desc: return 'Oxidoreductases'
    elif row.get('evalue', 1) > 1e-10: return 'Putative Specific Effectors'
    else: return 'Other Secreted Proteins'

def fraccionar_secretoma(df_diam, df_egg):
    print("\n[3/4] Fractionating Secretome Arsenal (DIAMOND + eggNOG)...")
    if df_diam.empty or df_egg.empty: return

    df_diam['Clean_ID'] = df_diam['qseqid'].str.split('.').str[0]
    df_egg['Clean_ID'] = df_egg['query'].str.split('.').str[0]

    df_cruce = pd.merge(df_diam, df_egg, on=['Clean_ID', 'Strain'], how='inner')
    df_cruce['Macro_Category'] = df_cruce.apply(clasificar_secretoma, axis=1)

    matriz_cat = pd.crosstab(df_cruce['Macro_Category'], df_cruce['Strain'])

    # Fig 3A: Heatmap
    plt.close('all')
    plt.figure(figsize=(10, 8))
    sns.heatmap(matriz_cat, cmap="YlOrRd", annot=True, fmt="d", linewidths=1)
    plt.title('Functional Architecture of the Secretome (Fig 3A)', fontsize=15, pad=20, fontweight='bold')
    plt.ylabel('Biological Macro-Category', fontweight='bold')
    plt.yticks(rotation=0)
    plt.savefig(os.path.join(OUT_FIGS, "Fig_3A_Secretome_Heatmap.svg"), format='svg', bbox_inches='tight')
    plt.close()

    # Fig 3B: CAZymes Breakdown
    cazy_list = []
    for _, row in df_cruce[df_cruce['CAZy'] != '-'].iterrows():
        for cz in str(row['CAZy']).split(','):
            clase = ''.join(filter(str.isalpha, cz.strip()))
            if clase: cazy_list.append({'Strain': row['Strain'], 'CAZy_Class': clase})

    if cazy_list:
        plt.close('all')
        df_cazy = pd.DataFrame(cazy_list)
        cazy_counts = pd.crosstab(df_cazy['CAZy_Class'], df_cazy['Strain'])
        cazy_counts.plot(kind='bar', figsize=(9, 6), colormap='Set2', width=0.7)
        plt.title('Distribution of Secreted CAZyme Families (Fig 3B)', pad=15, fontweight='bold')
        plt.ylabel('Number of Domains', fontweight='bold')
        plt.xlabel('CAZy Class', fontweight='bold')
        plt.xticks(rotation=0)
        sns.despine()
        plt.savefig(os.path.join(OUT_FIGS, "Fig_3B_Secretome_CAZymes.svg"), format='svg', bbox_inches='tight')
        plt.close()

    # Fig 3C-X: UpSet Plots per Macro-Category (Aplicando renderizado seguro)
    print("      Generating specific UpSet plots for each Secretome category...")
    for idx, cat in enumerate(df_cruce['Macro_Category'].unique()):
        df_cat = df_cruce[df_cruce['Macro_Category'] == cat]
        matriz_upset = pd.crosstab(df_cat['sseqid'], df_cat['Strain'])
        matriz_bool = (matriz_upset > 0).astype(bool)

        if len(matriz_bool.columns) > 1:
            try:
                upset_data_cat = matriz_bool.groupby(list(matriz_bool.columns)).size()
                fig = plt.figure(figsize=(10, 6))
                upset_plot(upset_data_cat, sort_by='cardinality', show_counts=True, fig=fig)
                plt.suptitle(f'Target Intersection: {cat}', fontweight='bold', fontsize=12, y=1.05)
                cat_safe = cat.replace('/', '_').replace(' ', '_').replace('(', '').replace(')', '')
                plt.savefig(os.path.join(OUT_FIGS, f"Fig_3C_UpSet_{cat_safe}.svg"), format='svg', bbox_inches='tight')
                plt.close(fig)
            except Exception as e:
                pass

    cols_out = ['Strain', 'qseqid', 'Macro_Category', 'sseqid', 'pident', 'CAZy', 'PFAMs', 'desc']
    df_cruce[cols_out].to_excel(os.path.join(OUT_TABS, "Table_S1_Master_Secretome.xlsx"), index=False)


# -----------------------------------------------------------------------------
# BLOCK 4: ML SUPER-MATRIX ASSEMBLY
# -----------------------------------------------------------------------------
def ensamblar_ml(m_egg):
    print("\n[4/4] Assembling Predictive Super-Matrix for Machine Learning...")
    matrices = [m for m in [m_egg] if not m.empty]
    if not matrices: return

    matriz_maestra = pd.concat(matrices, axis=0, join='outer').fillna(0).astype(int)
    n_cepas = len(matriz_maestra.columns)
    matriz_maestra['Sum'] = matriz_maestra.sum(axis=1)

    matriz_filtrada = matriz_maestra[(matriz_maestra['Sum'] > 0) & (matriz_maestra['Sum'] < n_cepas)].drop(columns=['Sum'])
    dataset_xgboost = matriz_filtrada.T
    ruta_ml = os.path.join(OUT_ML, "Table_S3_DATASET_XGBOOST.csv")
    dataset_xgboost.to_csv(ruta_ml, index_label="Strain_Sample")

    # Fig 4: Horizontal Bar Chart of Predictors Origin
    plt.close('all')
    sns.set_theme(style="ticks", context="paper", font_scale=1.2)

    origenes = matriz_filtrada.index.to_series().str.split('_').str[0].value_counts()

    plt.figure(figsize=(10, 6))
    ax = sns.barplot(x=origenes.values, y=origenes.index, palette='viridis')
    plt.title('Accessory Genome Architecture (ML Predictors Origin) - Fig 4', pad=15, fontweight='bold')
    plt.xlabel('Number of Features (Genes/Clusters)', fontweight='bold')
    plt.ylabel('Omics Dimension', fontweight='bold')
    sns.despine()

    plt.savefig(os.path.join(OUT_FIGS, "Fig_4_ML_Predictors_BarChart.svg"), format='svg', bbox_inches='tight')
    plt.close()

    print(f"  ✅ Super-Matrix Generated: {dataset_xgboost.shape[1]} predictors for {dataset_xgboost.shape[0]} strains.")

# -----------------------------------------------------------------------------
# MAIN EXECUTION
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    df_diam = procesar_diamond()
    df_egg, matriz_egg = procesar_eggnog()

    fraccionar_secretoma(df_diam, df_egg)

    ensamblar_ml(matriz_egg)

    print("\n🚀 PIPELINE COMPLETED. All Q1 English Figures and Tables are ready.")

"""##Matriz de Solapamiento Recíproco del Pangenoma (Heatmap)
**Descripción:**
Este script automatiza el procesamiento y la visualización de la matriz de presencia/ausencia global generada por OrthoFinder. Su objetivo es calcular y mapear el número total de ortogrupos proteicos homólogos compartidos de forma recíproca (par a par) entre los proteomas completos de las 18 especies del género *Botrytis*.

**Características del análisis:**
*   **Mapeo Taxonómico:** Traduce de forma automática los códigos internos de los archivos raw (`Bcine`, `Bacla`, etc.) a la nomenclatura binomial científica formal en cursiva.
*   **Anotación Cuantitativa:** Añade las etiquetas con los valores absolutos exactos de genes compartidos en cada celda de la matriz.
*   **Exportación Editorial:** Genera y exporta la gráfica final en alta resolución (`Figura_Heatmap_Pangenoma_Completo.jpg`), lista para su incorporación directa en la memoria o material suplementario.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# 1. Ruta de tu archivo en Google Drive
ruta_overlap = '/content/drive/MyDrive/TFM/Galaxy260-[OrthoFinder on dataset 230-247 and collection 229_ species overlaps].tsv'

if not os.path.exists(ruta_overlap):
    print(f"❌ Error: No se encuentra el archivo en la ruta: {ruta_overlap}")
else:
    # Leer matriz original
    df_overlap = pd.read_csv(ruta_overlap, sep='\t', index_col=0)

    # Diccionario de traducción de códigos a nombres científicos completos
    mapeo_especies = {
        'Bcine': 'Botrytis cinerea',
        'Bpseu': 'Botrytis pseudocinerea',
        'Bfaba': 'Botrytis fabae',
        'Bsqua': 'Botrytis squamosa',
        'Bacla': 'Botrytis aclada',
        'Bporr': 'Botrytis porri',
        'Bsino': 'Botrytis sinoallii',
        'Bbyss': 'Botrytis byssoidea',
        'Belli': 'Botrytis elliptica',
        'Btuli': 'Botrytis tulipae',
        'Bpaeo': 'Botrytis paeoniae',
        'Bhyac': 'Botrytis hyacinthi',
        'Bgala': 'Botrytis galanthina',
        'Bdewe': 'Botrytis deweyae',
        'Bfrag': 'Botrytis fragariae',
        'Beuro': 'Botrytis euroamericana',
        'Bmedu': 'Botrytis medusae',
        'Bfabi': 'Botrytis fabiopsis'
    }

    # Renombrar filas y columnas aplicando el mapa taxonómico
    df_overlap = df_overlap.rename(index=mapeo_especies, columns=mapeo_especies)

    # 2. Configuración estética de grado editorial
    fig, ax = plt.subplots(figsize=(15, 13))
    sns.set_theme(style="white")

    # Configuración de renderizado para tipografías vectoriales limpias
    plt.rcParams['svg.fonttype'] = 'none'

    # Dibujar el mapa de calor
    sns.heatmap(
        df_overlap,
        annot=True,
        fmt=".0f",
        cmap="Blues",
        linewidths=.6,
        cbar_kws={'label': 'Número de Ortogrupos Compartidos entre Proteomas'},
        annot_kws={"size": 9, "weight": "bold"}
    )

    # Títulos y formato de ejes
    plt.title("Matriz de Solapamiento del Pangenoma Global de Botrytis\n(Análisis de Homología de Secuencia Completa vía OrthoFinder)",
              fontsize=14, weight='bold', pad=25)
    plt.xlabel("Especies de Botrytis Analizadas", fontsize=12, weight='bold', labelpad=15)
    plt.ylabel("Especies de Botrytis Analizadas", fontsize=12, weight='bold', labelpad=15)

    # ¡Clave! Forzamos que las etiquetas de los ejes salgan en cursiva (itálica) como exige la nomenclatura biológica
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', weight='bold', style='italic', fontsize=11)
    ax.set_yticklabels(ax.get_yticklabels(), weight='bold', style='italic', fontsize=11)

    plt.tight_layout()

    # 3. Exportación simultánea (SVG vectorial para calidad infinita y PNG para vista rápida)
    PATH_RESULTS = os.path.dirname(ruta_overlap)

    ruta_svg = os.path.join(PATH_RESULTS, "Figura_Heatmap_Pangenoma_Completo.svg")
    ruta_png = os.path.join(PATH_RESULTS, "Figura_Heatmap_Pangenoma_Completo.png")

    plt.savefig(ruta_svg, format='svg', bbox_inches='tight')
    plt.savefig(ruta_png, dpi=300, bbox_inches='tight')
    plt.show()

    print("\n[✓] ¡Imágenes generadas con éxito con nomenclatura biológica formal!")
    print(f"💾 Vectorial (SVG) guardado en: {ruta_svg}")
    print(f"💾 Imagen (PNG) guardada en: {ruta_png}")

"""## Compartimentación Molecular del Pangenoma por Especie (Stacked Bar Chart)
**Descripción:**
Este script realiza la disección y cuantificación exacta de la arquitectura del pangenoma global de *Botrytis* a partir de los outputs crudos de OrthoFinder. El algoritmo analiza en paralelo la matriz de ortogrupos (`Galaxy254`) y el reporte de secuencias huérfanas o no asignadas (`Galaxy255`) para clasificar el proteoma completo de cada una de las 18 especies en tres compartimentos moleculares biológicamente independientes.

**Compartimentos analizados:**
1.  **Core Genome (Genoma Núcleo):** Familias de ortólogos altamente conservadas presentes de forma ubicua en el género ($\geq$ 17 especies evaluadas para mitigar sesgos de ensamblaje).
2.  **Accessory Genome (Genoma Accesorio):** Ortogrupos variables presentes en dos o más especies, pero sin llegar a la ubicuidad global (homologías compartidas y parálogos).
3.  **Specific Singletons (Componente Específico):** Genes de copia única exclusivos de cada taxón combinados con los genes huérfanos del reporte de *unassigned genes*.

**Exportación Editorial:** Genera la visualización de barras apiladas con una paleta de grado científico y exporta los resultados en formato vectorial escalable (`Figura_Barras_Pangenoma_Total.svg`) para garantizar una calidad de publicación óptima.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# 1. Definición de rutas a tus archivos reales de OrthoFinder
ruta_orthogroups = '/content/drive/MyDrive/TFM/Galaxy254-[OrthoFinder on dataset 230-247 and collection 229_ orthogroups (tsv)] (1).tsv'
ruta_unassigned = '/content/drive/MyDrive/TFM/Galaxy255-[OrthoFinder on dataset 230-247 and collection 229_ unassigned genes].tsv'

# Mapeo oficial de nombres en cursiva
mapeo_especies = {
    'Bcine': 'Botrytis cinerea', 'Bpseu': 'Botrytis pseudocinerea', 'Bfaba': 'Botrytis fabae',
    'Bsqua': 'Botrytis squamosa', 'Bacla': 'Botrytis aclada', 'Bporr': 'Botrytis porri',
    'Bsino': 'Botrytis sinoallii', 'Bbyss': 'Botrytis byssoidea', 'Belli': 'Botrytis elliptica',
    'Btuli': 'Botrytis tulipae', 'Bpaeo': 'Botrytis paeoniae', 'Bhyac': 'Botrytis hyacinthi',
    'Bgala': 'Botrytis galanthina', 'Bdewe': 'Botrytis deweyae', 'Bfrag': 'Botrytis fragariae',
    'Beuro': 'Botrytis euroamericana', 'Bmedu': 'Botrytis medusae', 'Bfabi': 'Botrytis fabiopsis'
}

if not os.path.exists(ruta_orthogroups) or not os.path.exists(ruta_unassigned):
    print("❌ Error: Verifica que los nombres de los archivos TSV subidos coincidan con las rutas.")
else:
    print("[►] Extrayendo arquitectura real del pangenoma completo...")

    # Cargar archivos de Galaxy
    df_og = pd.read_csv(ruta_orthogroups, sep='\t', index_col=0)
    df_un = pd.read_csv(ruta_unassigned, sep='\t', index_col=0)

    cepas = list(mapeo_especies.keys())

    # 2. Convertir matrices de texto a matrices binarias (1 si hay gen, 0 si está vacío)
    df_og_bin = df_og[cepas].notna().astype(int)
    df_un_bin = df_un[cepas].notna().astype(int)

    # Contar cuántas cepas tienen cada ortogrupo
    frecuencia_og = df_og_bin.sum(axis=1)

    # Clasificación formal de los Ortogrupos
    # Core Estricto (las 18 especies) u opción Soft-Core (>= 17 especies) para mitigar fallos de ensamblaje
    umbral_core = 17

    og_core = df_og_bin[frecuencia_og >= umbral_core]
    og_acc = df_og_bin[(frecuencia_og < umbral_core) & (frecuencia_og > 1)]
    og_sing = df_og_bin[frecuencia_og == 1]

    # Conteo de genes por compartimento para cada especie individual
    datos_grafico = []

    for c in cepas:
        # Contamos cuántas proteínas aporta esta especie a cada tipo de grupo
        # Para hacerlo exacto, extraemos el número real de secuencias (separadas por comas en las celdas del tsv)
        genes_core = df_og.loc[og_core.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        genes_acc = df_og.loc[og_acc.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()

        # Singletons de Ortogrupos específicos + Genes huérfanos unassigned (Galaxy255)
        genes_sing_og = df_og.loc[og_sing.index, c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        genes_sing_un = df_un[c].dropna().apply(lambda x: len(str(x).split(','))).sum()
        total_singletons = genes_sing_og + genes_sing_un

        datos_grafico.append({
            'Especie': mapeo_especies[c],
            'Core Genome': genes_core,
            'Accessory Genome': genes_acc,
            'Specific Singletons': total_singletons
        })

    df_resultados = pd.DataFrame(datos_grafico).set_index('Especie')

    # Mostrar resumen cuantitativo en consola
    print("\n[✓] Análisis molecular completado. Resumen promedidado del Genoma Completo:")
    print(df_resultados.mean().to_string())

    # 3. GENERACIÓN DE LA FIGURA DE BARRAS APILADAS (FORMATO EDITORIAL SVG)
    fig, ax = plt.subplots(figsize=(14, 9))
    plt.rcParams['svg.fonttype'] = 'none'

    # Paleta de grado científico: Azul oscuro (Core), Azul medio (Accesorio), Celeste/Gris claro (Singletons)
    colores = ['#1b365d', '#4b779a', '#aed1e6']

    df_resultados.plot(kind='bar', stacked=True, color=colores, ax=ax, width=0.7, edgecolor='black', linewidth=0.5)

    # Configuración del gráfico
    plt.title("Compartimentación del Pangenoma Global del Género Botrytis\n(Distribución de Genes Totales por Especie)", fontsize=14, weight='bold', pad=20)
    plt.xlabel("Especies Analizadas (Genoma Completo)", fontsize=12, weight='bold', labelpad=15)
    plt.ylabel("Número Total de Genes Anotados", fontsize=12, weight='bold', labelpad=15)

    # Leyenda formal
    plt.legend(['Core Genome (Conservado $\geq$17 spp.)', 'Accessory Genome (Variables)', 'Specific Singletons (Únicos / Huérfanos)'],
               loc='lower left', frameon=True, facecolor='white', edgecolor='none')

    # Forzar nombres científicos en cursiva en el eje X
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', weight='bold', style='italic', fontsize=11)
    plt.yticks(weight='bold')
    plt.grid(axis='y', linestyle='--', alpha=0.5)

    plt.tight_layout()

    # Exportar en SVG y PNG
    PATH_RESULTS = os.path.dirname(ruta_orthogroups)
    ruta_svg = os.path.join(PATH_RESULTS, "Figura_Barras_Pangenoma_Total.svg")
    ruta_png = os.path.join(PATH_RESULTS, "Figura_Barras_Pangenoma_Total.png")

    plt.savefig(ruta_svg, format='svg', bbox_inches='tight')
    plt.savefig(ruta_png, dpi=300, bbox_inches='tight')
    plt.show()

    print(f"\n💾 ¡Figura de barras apiladas guardada en SVG vectorial!: {ruta_svg}")

"""## Consolidación Estructurada de la Anotación Funcional Global (eggNOG-mapper)
**Descripción:** Este script automatiza la unificación y el formateo bioinformático de los reportes funcionales en bruto (`.tabular`) generados de forma individual para cada una de las 18 especies de *Botrytis* mediante la plataforma eggNOG-mapper v2.1.2.

El algoritmo realiza un parseo iterativo de la colección de archivos, aplica un filtro automatizado para remover las líneas de comentarios informáticos iniciales (metadatos encabezados por `#`) y rescata las cabeceras originales del pipeline de Galaxy. Finalmente, clasifica las anotaciones construyendo un único libro de Excel multipestaña donde cada hoja se renombra bajo la estricta nomenclatura binomial científica (*Género especie*), sirviendo como la base de datos funcional curada del proyecto.

**Criterios de Calidad Implementados:**
* **Filtro Homólogo:** Mapeo unívoco de los códigos de cepa crudos (`Bcine`, `Bdewe`, etc.) a sus identidades taxonómicas formales.
* **Limpieza de Ruido:** Eliminación de directivas de ejecución informáticas para conservar únicamente las matrices de anotación de grano fino.
* **Soporte Editorial:** Generación automática de la base de datos en un archivo de Excel consolidado (`Tabla_Suplementaria_S2_Anotacion_GO.xlsx`) listo para su depósito como material suplementario transferible.
"""

import os
import glob
import pandas as pd

# 1. Configuración de rutas dentro de tu Google Drive
CARPETA_EGGNOG = '/content/drive/MyDrive/TFM/eggNOG Mapper on collection 229_ annotations/'
RUTA_SALIDA_EXCEL = '/content/drive/MyDrive/TFM/Tabla_Suplementaria_S3_Anotacion_GO.xlsx'

# Diccionario oficial de mapeo taxonómico formal para renombrar las páginas del PDF/Excel
mapeo_especies = {
    'Bacla': 'Botrytis aclada',
    'Bbyss': 'Botrytis byssoidea',
    'Bcine': 'Botrytis cinerea',
    'Bdewe': 'Botrytis deweyae',
    'Belli': 'Botrytis elliptica',
    'Beuro': 'Botrytis euroamericana',
    'Bfaba': 'Botrytis fabae',
    'Bfabi': 'Botrytis fabiopsis',
    'Bfrag': 'Botrytis fragariae',
    'Bgala': 'Botrytis galanthina',
    'Bhyac': 'Botrytis hyacinthi',
    'Bmedu': 'Botrytis medusae',
    'Bpaeo': 'Botrytis paeoniae',
    'Bporr': 'Botrytis porri',
    'Bpseu': 'Botrytis pseudocinerea',
    'Bsino': 'Botrytis sinoallii',
    'Bsqua': 'Botrytis squamosa',
    'Btuli': 'Botrytis tulipae'
}

# Buscar de forma masiva todos los reportes .tabular o .tsv en la carpeta
archivos_input = glob.glob(os.path.join(CARPETA_EGGNOG, "*.tabular")) + glob.glob(os.path.join(CARPETA_EGGNOG, "*.tsv"))

if len(archivos_input) == 0:
    print(f"❌ Error: No se detectaron archivos .tabular en la ruta especificada: {CARPETA_EGGNOG}")
    print("Por favor, revisa que el nombre de la carpeta en tu Drive coincida exactamente.")
else:
    print(f"[►] Iniciando la unificación de {len(archivos_input)} reportes funcionales...")

    # Abrir el escritor multi-pestaña de Excel
    with pd.ExcelWriter(RUTA_SALIDA_EXCEL, engine='openpyxl') as writer:

        for ruta_archivo in sorted(archivos_input):
            nombre_archivo = os.path.basename(ruta_archivo)

            # Identificar el código de la cepa dentro del nombre del archivo
            cepa_detectada = None
            for codigo in mapeo_especies.keys():
                if codigo in nombre_archivo:
                    cepa_detectada = codigo
                    break

            if cepa_detectada:
                nombre_pestaña = mapeo_especies[cepa_detectada]
                # Limitación técnica de Excel: las pestañas no pueden superar los 31 caracteres
                nombre_pestaña_corta = nombre_pestaña[:31]

                try:
                    # 2. Lectura omitiendo las líneas informáticas de comentarios que empiezan con '#'
                    df_temp = pd.read_csv(ruta_archivo, sep='\t', comment='#', header=None)

                    # 3. Rescate de las cabeceras de columnas reales que eggNOG guarda en la línea '#query'
                    columnas = None
                    with open(ruta_archivo, 'r') as f:
                        for line in f:
                            if line.startswith('#query') or line.startswith('# query'):
                                # Limpiamos el símbolo '#' y el espacio sobrante
                                columnas = line.strip().replace('#', '').strip().split('\t')
                                break

                    # Si las columnas extraídas coinciden con el tamaño de la matriz, las asignamos
                    if columnas and len(columnas) == df_temp.shape[1]:
                        df_temp.columns = columnas
                    else:
                        # Cabecera por defecto en caso de anomalía en el archivo raw
                        df_temp.columns = [f"Col_{i}" for i in range(df_temp.shape[1])]

                    # 4. Guardar los datos limpios en la hoja correspondiente a la especie
                    df_temp.to_excel(writer, sheet_name=nombre_pestaña_corta, index=False)
                    print(f"   ✓ Pestaña consolidada con éxito: {nombre_pestaña} ({df_temp.shape[0]} genes anotados)")

                except Exception as e:
                    print(f"   ⚠️ No se pudo procesar el archivo {nombre_archivo} debido a: {e}")
            else:
                print(f"   ⚠️ Archivo omitido (no corresponde a ninguna de las 18 especies): {nombre_archivo}")

    print(f"\n[✓] ¡Proceso finalizado!")
    print(f"💾 Libro de Excel unificado y guardado en: {RUTA_SALIDA_EXCEL}")