# -*- coding: utf-8 -*-
"""Códigos_TFM_Módulo_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYRZG6xtwt4wEmZr4PEnoNQwcMoha0FU

**Módulo 3: Reperfilamiento del Secretoma, Clasificación de CAZymas y Caracterización de Determinantes Efectores**

Este módulo se centra en diseccionar los elementos proteicos secretados y los perfiles funcionales globales implicados en la interacción directa con el huésped vegetal.

Contenedores Evolutivos por DIAMOND: Procesa los alineamientos masivos del secretoma mediante DIAMOND, segregando los targets en contenedores evolutivos según su rango de identidad peptídica (Divergent: 70-80%, Conserved: 80-90%, High Identity: >98%) para identificar tasas de divergencia adaptativa rápida.

Anotación Masiva de Ortólogos vía eggNOG: Extrae de forma exhaustiva los Grupos Ortólogos (OGs), anotaciones de la Comisión de Enzimas (EC Numbers) y categorías del catálogo oficial COG (mapeando un diccionario estructurado de 26 categorías funcionales) a partir de los reportes de eggNOG-mapper.

Tipado de Familias CAZyme: Rastrea e integra la abundancia y distribución de enzimas activas sobre carbohidratos (CAZymes), clasificando las secuencias por macro-categorías funcionales para comprender los mecanismos de degradación de la pared celular vegetal.

Visualización e Intersección del Secretoma: Genera diagramas de distribución de clases enzimáticas (Seaborn) y plots de UpSet combinatorios específicos por macro-categoría para revelar qué componentes del repertorio efector y enzimático son cepa-específicos o compartidos.
"""

import os
import warnings
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import IsolationForest

warnings.filterwarnings('ignore')

# 0. CONFIGURACIÓN DEL ENTORNO
print("Conectando al sistema de archivos y configurando directorios...")
os.system("fusermount -u /content/drive 2>/dev/null")
os.system("rm -rf /content/drive")
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

PATH_BASE = '/content/drive/MyDrive/TFM'
PATH_ML_OUT = os.path.join(PATH_BASE, "Modelos_ML")
os.makedirs(PATH_ML_OUT, exist_ok=True)

# 1. CARGA Y CURACIÓN DE DATOS
print("Cargando matrices de pangenoma y metadatos fenotípicos...")
df_anti_raw = pd.read_pickle(os.path.join(PATH_BASE, "antismash/Resultados_Pangenomicos_Final/Data_Machine_Learning_ML.pkl"))
df_egg = pd.read_csv(os.path.join(PATH_BASE, "Results_Machine_Learning/Table_S3_DATASET_XGBOOST.csv"), index_col=0)
df_y = pd.read_csv(os.path.join(PATH_BASE, 'Fenotipo_Multiclase.csv'), index_col=0)

def normalizar_taxonomia(n):
    return str(n).replace("Botrytis_", "B").replace(" ", "").strip()

df_egg.index = [normalizar_taxonomia(x) for x in df_egg.index]
df_anti_raw['Species'] = df_anti_raw['Species'].apply(normalizar_taxonomia)

# Mapeo de cepa a hospedador (Nicho ecológico)
mapa_hospedador = df_y['Fenotipo'].to_dict()

# 2. ESPACIO GENÓMICO CORE (eggNOG) Y DETECCIÓN DE ANOMALÍAS
print("Construyendo espacio genómico basal (eggNOG)...")
X_egg = df_egg.fillna(0)

# Filtro de control de calidad para evitar quimeras o contaminación
iso_v31 = IsolationForest(contamination=0.01, random_state=42)
iso_v31.fit(X_egg)

# 3. ESPACIO DE METABOLISMO SECUNDARIO (antiSMASH - TF-IDF)
print("Construyendo espacio de clusters biosintéticos ponderados (TF-IDF)...")
df_anti_mat = pd.crosstab(df_anti_raw['Species'], df_anti_raw['Homology_Family'])
df_anti_mat = (df_anti_mat > 0).astype(int)
X_anti = df_anti_mat.reindex(X_egg.index, fill_value=0)

# Factor de rareza (IDF) para penalizar familias génicas ubicuas
N_especies = len(X_anti)
prevalencia = X_anti.sum(axis=0)
idf_bgc = {fam: np.log((N_especies + 1) / (p + 1)) + 1 for fam, p in prevalencia.items()}

# Vectorización TF-IDF final
X_anti_tfidf = X_anti.copy()
for col in X_anti_tfidf.columns:
    X_anti_tfidf[col] = X_anti_tfidf[col] * idf_bgc[col]

# Diccionario de secuencias representativas para inferencia rápida
df_anti_raw['temp_len'] = df_anti_raw['Core_Sequence'].str.len()
mapa_secuencias = (df_anti_raw.sort_values(by='temp_len', ascending=False)
                   .drop_duplicates('Homology_Family')
                   .set_index('Homology_Family')['Core_Sequence'].to_dict())

# 4. EXPORTACIÓN DEL ENTORNO PANGENÓMICO
modelo_estructurado = {
    'matriz_egg': X_egg,
    'matriz_anti_tfidf': X_anti_tfidf,
    'mapa_hospedador': mapa_hospedador,
    'mapa_secuencias': mapa_secuencias,
    'idf_bgc': idf_bgc,
    'modelo_outliers': iso_v31
}

ruta_guardado = os.path.join(PATH_ML_OUT, 'master_botrytis_v31.pkl')
joblib.dump(modelo_estructurado, ruta_guardado)
print(f"Cerebro genómico v31 compilado y guardado en: {ruta_guardado}")