# -*- coding: utf-8 -*-
"""Códigos_TFM_Módulo_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lf2pCau1dgruWXBRQ2gKAxNP7a4lP-G_

**Módulo 5: Clasificación predictiva de patogenicidad y descubrimiento de biomarcadores vía inteligencia artificial explicable**

El módulo final del pipeline constituye el núcleo predictivo y analítico del TFM, integrando técnicas de aprendizaje supervisado con metodologías avanzadas de explicabilidad en bioinformática.

Ensamblado de la súper-matriz predictiva

Se construye una matriz predictiva de alta dimensionalidad que integra de forma unificada todos los predictores biológicos e indicadores moleculares generados en los módulos anteriores.

Este ensamblaje da lugar a un dataset robusto con más de 1500 variables explicativas, estructurado a nivel de cepa, que captura simultáneamente información genómica, funcional y metabólica.

Entrenamiento XGBoost de alta sensibilidad

Sobre la matriz consolidada se entrena un modelo supervisado multiclase basado en XGBoost (xgb.XGBClassifier), configurado específicamente para escenarios de alta dimensionalidad y tamaño muestral reducido.

El modelo se optimiza mediante un esquema de regularización y control de complejidad estructural, utilizando parámetros como:

profundidad máxima (max_depth = 6)
tasa de aprendizaje (learning_rate = 0.3)
submuestreo por columnas (colsample_bytree = 0.8)

Este ajuste fuerza al modelo a capturar patrones discretos asociados a variantes biosintéticas y perfiles de efectores relevantes para la patogenicidad, minimizando el riesgo de sobreajuste.

Explicabilidad y descubrimiento de biomarcadores mediante SHAP

El modelo entrenado se acopla a la librería SHAP (SHapley Additive exPlanations), basada en teoría de juegos cooperativos, para interpretar las predicciones a nivel de variable individual.

Se calculan valores de Shapley que cuantifican la contribución de cada característica a la predicción final, permitiendo descomponer el impacto de:

- clústeres biosintéticos
- enzimas funcionales
- dominios secretados

sobre la clasificación del fenotipo patogénico o el rango de hospedadores.

Los resultados se visualizan mediante gráficos de importancia global (shap.summary_plot), que permiten identificar biomarcadores genómicos con mayor capacidad discriminativa dentro del modelo.

Reportes de grado científico

El pipeline finaliza con la exportación automatizada de los resultados en un formato estructurado, generando un archivo maestro (Table_S4_XGBoost_Predictions.xlsx) que incluye predicciones, métricas y variables relevantes.

Este output constituye el reporte analítico final del estudio, directamente integrable en el manuscrito para su presentación y discusión científica.
"""

"""
=============================================================================
BLOQUE 3: MACHINE LEARNING (XGBOOST) & EXPLICABILIDAD SHAP (Q1 QUALITY)
=============================================================================
Integra la genómica core (eggNOG) y el metabolismo secundario (BGCs) en una
súper-matriz. Entrena un clasificador XGBoost mitigado para alta dimensionalidad
y utiliza SHAP para revelar los verdaderos determinantes de patogenicidad.
=============================================================================
"""

import os, glob, zipfile, tempfile, shutil, difflib
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
import shap
from sklearn.preprocessing import LabelEncoder
from Bio import SeqIO
import warnings

warnings.filterwarnings('ignore')

def ejecutar_ml_y_shap():
    print("\n[1/4] Loading Super-Matrix and Master Data...")
    PATH_BASE = '/content/drive/MyDrive/TFM'
    PATH_SUJETOS = os.path.join(PATH_BASE, 'sujetos')
    OUT_ML = os.path.join(PATH_BASE, "Results_Machine_Learning_English")
    os.makedirs(OUT_ML, exist_ok=True)

    # 1. Cargar datos del pipeline base
    ruta_bundle = os.path.join(PATH_BASE, 'Modelos_ML', 'master_botrytis_v31.pkl')
    if not os.path.exists(ruta_bundle):
        print(f"❌ Error: No se encuentra el archivo maestro en {ruta_bundle}")
        return

    bundle = joblib.load(ruta_bundle)
    X_egg = bundle['matriz_egg']
    X_anti_tfidf = bundle['matriz_anti_tfidf']
    mapa_hospedador = bundle['mapa_hospedador']
    mapa_secuencias = bundle['mapa_secuencias']

    # 2. Binarizar BGCs y fusionar (Súper-Matriz X)
    X_anti_bin = (X_anti_tfidf > 0).astype(int)
    # Añadimos prefijo BGC_ para distinguir claramente las familias en la gráfica SHAP
    X_anti_bin.columns = ["BGC_" + str(c) for c in X_anti_bin.columns]

    # Fusión Core (eggNOG) y Secundario (BGCs)
    X_train = pd.concat([X_egg, X_anti_bin], axis=1).fillna(0).astype(int)

    # 3. Preparar la variable objetivo (y: El Huésped)
    y_labels = [mapa_hospedador.get(sp, 'Desconocido') for sp in X_train.index]
    le = LabelEncoder()
    y_train = le.fit_transform(y_labels)

    print(f"      -> Super-Matrix assembled: {X_train.shape[1]} features across {X_train.shape[0]} strains.")

    # =====================================================================
    # ENTRENAMIENTO XGBOOST (MITIGADO CONTRA OVERFITTING)
    # =====================================================================
    # =====================================================================
    # ENTRENAMIENTO XGBOOST: ENFOQUE DE ALTA SENSIBILIDAD
    # =====================================================================
    print("\n[2/4] Training XGBoost (High Sensitivity Mode)...")

    model = xgb.XGBClassifier(
        objective='multi:softprob',
        num_class=len(le.classes_),
        n_estimators=100,          # Menos árboles pero más potentes
        max_depth=6,               # Aumentamos profundidad para que encuentre los BGCs específicos
        learning_rate=0.3,         # Aprendizaje más agresivo para forzar la diferenciación
        colsample_bytree=0.8,      # Que vea casi todos los genes (80%) para que no se pierda nada
        subsample=1.0,             # Usamos todos los datos disponibles
        reg_alpha=0,               # Quitamos la penalización L1 para que no borre variables
        reg_lambda=1.0,            # Mantenemos L2 para estabilidad
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42
    )

    # Entrenamos SIN pesos de clase esta vez para ver si recuperamos la base
    model.fit(X_train, y_train)

    # =====================================================================
    # EXPLICABILIDAD SHAP
    # =====================================================================
    print("\n[3/4] Extracting Biological Relevance via SHAP...")

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_train)

    plt.close('all')
    plt.figure(figsize=(12, 8))

    shap.summary_plot(
        shap_values,
        X_train,
        plot_type="bar",
        class_names=le.classes_,
        show=False
    )

    plt.title("Top Pathogenicity Determinants (SHAP Feature Importance)", pad=20, fontweight='bold', fontsize=14)
    plt.xlabel("Mean Absolute Impact on Prediction (SHAP value)", fontsize=12)
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_ML, "Fig_5_SHAP_Host_Specificity.svg"), format='svg', bbox_inches='tight', dpi=300)
    plt.close()

    print("      -> SHAP plot saved: Fig_5_SHAP_Host_Specificity.svg")

    # =====================================================================
    # PREDICCIÓN CIEGA DE SUJETOS
    # =====================================================================
    print("\n[4/4] AI Blind Prediction on Unknown Subjects...")
    carpetas = [d for d in os.listdir(PATH_SUJETOS) if os.path.isdir(os.path.join(PATH_SUJETOS, d))]
    resultados_ml = []

    for id_hongo in carpetas:
        ruta = os.path.join(PATH_SUJETOS, id_hongo)
        f_egg = glob.glob(os.path.join(ruta, "*.txt"))
        f_anti = glob.glob(os.path.join(ruta, "*.zip"))
        if not f_egg or not f_anti: continue

        # Vector vacío para el sujeto
        v_sujeto = pd.DataFrame(0, index=[id_hongo], columns=X_train.columns)

        # Rellenar Core (eggNOG)
        df_e = pd.read_csv(f_egg[0], sep='\t', comment='#', header=None)
        genes_egg = ["eggNOG_" + str(x).split(',')[0] for x in df_e[4].dropna().unique() if x != '-']
        for g in genes_egg:
            if g in v_sujeto.columns: v_sujeto.at[id_hongo, g] = 1

        # Rellenar BGCs con cortafuegos del 85%
        tmp = tempfile.mkdtemp()
        with zipfile.ZipFile(f_anti[0], 'r') as z: z.extractall(tmp)

        for gbk in glob.glob(os.path.join(tmp, "**", "*.gbk"), recursive=True):
            prot_sec_core = ""
            try:
                record = SeqIO.read(gbk, "genbank")
                for feat in record.features:
                    if feat.type == "CDS":
                        gen_txt = str(feat.qualifiers).lower()
                        gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()
                        traduccion = feat.qualifiers.get('translation', [''])[0]

                        is_core = (gene_kind == 'biosynthetic') or any(k in gen_txt for k in [
                            'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
                            'terpene synthase', 'terpene cyclase'
                        ])

                        if is_core and len(traduccion) > len(prot_sec_core):
                            prot_sec_core = traduccion

                if prot_sec_core:
                    encontrado = False
                    for f, s_ref in mapa_secuencias.items():
                        str_ref = str(s_ref)
                        if str_ref in prot_sec_core or prot_sec_core in str_ref:
                            bgc_col = "BGC_" + f
                            if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                            encontrado = True
                            break

                    if not encontrado:
                        for f, s_ref in mapa_secuencias.items():
                            str_ref = str(s_ref)
                            L1, L2 = len(prot_sec_core), len(str_ref)
                            # BARRERA ESTRICTA (0.85) CONTRA FALSOS POSITIVOS
                            if L1 > 0 and L2 > 0 and (min(L1, L2) / max(L1, L2)) >= 0.85:
                                if difflib.SequenceMatcher(None, prot_sec_core, str_ref).ratio() >= 0.85:
                                    bgc_col = "BGC_" + f
                                    if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                                    break
            except Exception:
                pass

        shutil.rmtree(tmp)

        # Predicción XGBoost
        probs = model.predict_proba(v_sujeto)[0]
        idx_pred = np.argmax(probs)
        huesped_predicho = le.inverse_transform([idx_pred])[0]
        confianza_ia = probs[idx_pred] * 100

        # Filtro final: Si no hay firmas de BGCs, es un Outgroup/Falso Positivo
        bgcs_encontrados = v_sujeto[[c for c in v_sujeto.columns if c.startswith("BGC_")]].sum(axis=1).values[0]
        if bgcs_encontrados == 0:
            huesped_predicho = "Indeterminado / Outgroup (Sin Firmas BGC)"
            confianza_ia = 0.0

        resultados_ml.append({
            "Muestra / Sujeto": id_hongo,
            "Predicción Huésped (XGBoost)": huesped_predicho,
            "Confianza Algoritmo (%)": round(confianza_ia, 2),
            "BGCs Clave Detectados": bgcs_encontrados
        })

    df_final_ml = pd.DataFrame(resultados_ml)
    df_final_ml.to_excel(os.path.join(OUT_ML, "Table_S4_XGBoost_Predictions.xlsx"), index=False)

    print("\n✅ AI Predictive Report Generated Successfully!")
    print(df_final_ml.to_string())

if __name__ == "__main__":
    ejecutar_ml_y_shap()

# =============================================================================
# BLOQUE 3: MACHINE LEARNING (XGBOOST) & EXPLICABILIDAD SHAP (Q1 QUALITY)
# =============================================================================
# Integra la genómica core (eggNOG) y el metabolismo secundario (BGCs) en una
# súper-matriz. Entrena un clasificador XGBoost mitigado para alta dimensionalidad
# y utiliza SHAP para revelar los verdaderos determinantes de patogenicidad.
# =============================================================================

import os, glob, zipfile, tempfile, shutil, difflib
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
from Bio import SeqIO
import warnings

# Asegurar la presencia de la librería SHAP en el entorno
try:
    import shap
except ImportError:
    !pip install shap -q
    import shap

warnings.filterwarnings('ignore')

def ejecutar_ml_y_shap():
    print("\n[1/4] Cargando Súper-Matriz y Datos Maestros del Pangenoma...")
    PATH_BASE = '/content/drive/MyDrive/TFM'
    PATH_SUJETOS = os.path.join(PATH_BASE, 'sujetos')
    OUT_ML = os.path.join(PATH_BASE, "Resultados_Machine_Learning")
    os.makedirs(OUT_ML, exist_ok=True)

    # 1. Cargar el objeto serializado del pipeline previo
    ruta_bundle = os.path.join(PATH_BASE, 'Modelos_ML', 'master_botrytis_v31.pkl')
    if not os.path.exists(ruta_bundle):
        print(f"❌ Error: No se localiza el archivo maestro consolidado en {ruta_bundle}")
        return

    bundle = joblib.load(ruta_bundle)
    X_egg = bundle['matriz_egg']
    X_anti_tfidf = bundle['matriz_anti_tfidf']
    mapa_hospedador = bundle['mapa_hospedador']
    mapa_secuencias = bundle['mapa_secuencias']

    # 2. Binarizar BGCs y concatenar componentes (Construcción de la Súper-Matriz X)
    X_anti_bin = (X_anti_tfidf > 0).astype(int)
    # Se añade el prefijo bionformático 'BGC_' para discriminación visual clara en la gráfica SHAP
    X_anti_bin.columns = ["BGC_" + str(c) for c in X_anti_bin.columns]

    # Fusión del Genoma Núcleo (eggNOG) y Genoma Accesorio Metabólico (BGCs)
    X_train = pd.concat([X_egg, X_anti_bin], axis=1).fillna(0).astype(int)

    # 3. Codificación de la variable objetivo predictiva (y: Rango de Hospedadores)
    y_labels = [mapa_hospedador.get(sp, 'Desconocido') for sp in X_train.index]
    le = LabelEncoder()
    y_train = le.fit_transform(y_labels)

    print(f"      -> Súper-Matriz ensamblada con éxito: {X_train.shape[1]} características moleculares distribuidas en {X_train.shape[0]} cepas fúngicas.")

    # =====================================================================
    # ENTRENAMIENTO XGBOOST (CONFIGURACIÓN DE ALTA SENSIBILIDAD)
    # =====================================================================
    print("\n[2/4] Entrenando Clasificador XGBoost (Modo Alta Sensibilidad Pangenómica)...")

    model = xgb.XGBClassifier(
        objective='multi:softprob',
        num_class=len(le.classes_),
        n_estimators=100,          # Arquitectura balanceada de árboles de decisión optimizados
        max_depth=6,               # Profundidad calibrada para interceptar topologías complejas de BGCs
        learning_rate=0.3,         # Tasa de aprendizaje moderadamente agresiva para forzar la convergencia funcional
        colsample_bytree=0.8,      # Fracción del 80% de variables por árbol para evitar exclusiones biológicas
        subsample=1.0,             # Muestreo poblacional íntegro para maximizar estabilidad evolutiva
        reg_alpha=0,               # Desactivación de regularización L1 para conservar variables minoritarias
        reg_lambda=1.0,            # Regularización L2 activa para el control de varianza estructural
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42
    )

    # Ajuste del modelo sobre el conjunto global pangenómico
    model.fit(X_train, y_train)
    print("      -> Algoritmo XGBoost convergido y entrenado.")

    # =====================================================================
    # EXPLICABILIDAD GENÓMICA MEDIANTE VALORES SHAP
    # =====================================================================
    print("\n[3/4] Extrayendo Determinantes Biológicos de Patogenicidad vía SHAP...")

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_train)

    plt.close('all')
    fig = plt.figure(figsize=(12, 8), dpi=300)

    # Adaptación técnica de la API de SHAP para modelos multiclase (Visualización global de peso de características)
    # En estructuras de salida tridimensionales de XGBoost multiclase, tomamos la magnitud global ponderada
    if isinstance(shap_values, list):
        shap_to_plot = shap_values
    elif len(shap_values.shape) == 3:
        # Colapsar dimensiones para obtener la importancia absoluta global promedio entre clases
        shap_to_plot = np.abs(shap_values).mean(axis=2)
    else:
        shap_to_plot = shap_values

    # Generación del gráfico de barras de importancia de características con SHAP
    shap.summary_plot(
        shap_to_plot,
        X_train,
        plot_type="bar",
        class_names=le.classes_,
        max_display=15,
        show=False
    )

    # Maquetación con formato editorial científico
    plt.title("Determinantes Biológicos Clave de Patogenicidad (Importancia Funcional SHAP)", pad=25, fontweight='bold', fontsize=14)
    plt.xlabel("Impacto Medio Absoluto en la Predicción del Hospedador (Magnitud del valor SHAP)", fontsize=12, labelpad=12)
    plt.rc('font', family='sans-serif', size=11)

    # Exportación automática en formato vectorial de alta resolución (SVG)
    plt.tight_layout()
    ruta_figura_salida = os.path.join(OUT_ML, "Fig_5_SHAP_Host_Specificity.svg")
    plt.savefig(ruta_figura_salida, format='svg', bbox_inches='tight', dpi=300)
    plt.close()

    print(f"      -> Gráfica vectorial SHAP exportada con éxito en: {ruta_figura_salida}")

    # =====================================================================
    # PREDICCIÓN CIEGA DE SUJETOS DESCONOCIDOS
    # =====================================================================
    print("\n[4/4] Ejecutando Predicción Ciega por Inteligencia Artificial en Sujetos de Validación...")

    if not os.path.exists(PATH_SUJETOS):
        print(f"⚠️ Alerta: El directorio de validación ciega '{PATH_SUJETOS}' no existe. Omitiendo paso.")
        return

    carpetas = [d for d in os.listdir(PATH_SUJETOS) if os.path.isdir(os.path.join(PATH_SUJETOS, d))]
    resultados_ml = []

    for id_hongo in carpetas:
        ruta = os.path.join(PATH_SUJETOS, id_hongo)
        f_egg = glob.glob(os.path.join(ruta, "*.txt"))
        f_anti = glob.glob(os.path.join(ruta, "*.zip"))
        if not f_egg or not f_anti: continue

        # Inicialización de un vector vacío estructurado con las dimensiones de la súper-matriz de entrenamiento
        v_sujeto = pd.DataFrame(0, index=[id_hongo], columns=X_train.columns)

        # Parseo y codificación binaria de componentes del Genoma Núcleo (eggNOG)
        df_e = pd.read_csv(f_egg[0], sep='\t', comment='#', header=None)
        genes_egg = ["eggNOG_" + str(x).split(',')[0] for x in df_e[4].dropna().unique() if x != '-']
        for g in genes_egg:
            if g in v_sujeto.columns: v_sujeto.at[id_hongo, g] = 1

        # Extracción y parseo de clústeres biosintéticos (BGCs) con cortafuegos de identidad
        tmp = tempfile.mkdtemp()
        with zipfile.ZipFile(f_anti[0], 'r') as z: z.extractall(tmp)

        for gbk in glob.glob(os.path.join(tmp, "**", "*.gbk"), recursive=True):
            prot_sec_core = ""
            try:
                record = SeqIO.read(gbk, "genbank")
                for feat in record.features:
                    if feat.type == "CDS":
                        gen_txt = str(feat.qualifiers).lower()
                        gene_kind = feat.qualifiers.get('gene_kind', [''])[0].lower()
                        traduccion = feat.qualifiers.get('translation', [''])[0]

                        is_core = (gene_kind == 'biosynthetic') or any(k in gen_txt for k in [
                            'nrps', 'non-ribosomal peptide', 'polyketide synthase', 'pks',
                            'terpene synthase', 'terpene cyclase'
                        ])

                        if is_core and len(traduccion) > len(prot_sec_core):
                            prot_sec_core = traduccion

                if prot_sec_core:
                    encontrado = False
                    for f, s_ref in mapa_secuencias.items():
                        str_ref = str(s_ref)
                        if str_ref in prot_sec_core or prot_sec_core in str_ref:
                            bgc_col = "BGC_" + f
                            if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                            encontrado = True
                            break

                    if not encontrado:
                        for f, s_ref in mapa_secuencias.items():
                            str_ref = str(s_ref)
                            L1, L2 = len(prot_sec_core), len(str_ref)
                            # CORTAFUEGOS BIOLÓGICO ESTRICTO (>= 85% identidad de longitud y alineamiento)
                            if L1 > 0 and L2 > 0 and (min(L1, L2) / max(L1, L2)) >= 0.85:
                                if difflib.SequenceMatcher(None, prot_sec_core, str_ref).ratio() >= 0.85:
                                    bgc_col = "BGC_" + f
                                    if bgc_col in v_sujeto.columns: v_sujeto.at[id_hongo, bgc_col] = 1
                                    break
            except Exception:
                pass

        shutil.rmtree(tmp)

        # Inferencia probabilística mediante el modelo XGBoost
        probs = model.predict_proba(v_sujeto)[0]
        idx_pred = np.argmax(probs)
        huesped_predicho = le.inverse_transform([idx_pred])[0]
        confianza_ia = probs[idx_pred] * 100

        # Filtro de seguridad evolutivo: Si carece de firmas de BGCs homólogos, se declara Outgroup
        bgcs_encontrados = v_sujeto[[c for c in v_sujeto.columns if c.startswith("BGC_")]].sum(axis=1).values[0]
        if bgcs_encontrados == 0:
            huesped_predicho = "Indeterminado / Outgroup (Sin Firmas Metabo-Secundarias BGC)"
            confianza_ia = 0.0

        resultados_ml.append({
            "Muestra / Sujeto": id_hongo,
            "Predicción Huésped (XGBoost)": huesped_predicho,
            "Confianza Algoritmo (%)": round(confianza_ia, 2),
            "BGCs Clave Detectados": bgcs_encontrados
        })

    df_final_ml = pd.DataFrame(resultados_ml)
    ruta_tabla_salida = os.path.join(OUT_ML, "Tabla_S4_Predicciones_XGBoost.xlsx")
    df_final_ml.to_excel(ruta_tabla_salida, index=False)

    print("\n✅ ¡Informe Predictivo de Inteligencia Artificial Generado con Éxito!")
    print(f"💾 Reporte consolidado exportado a Excel en: {ruta_tabla_salida}\n")
    print(df_final_ml.to_string(index=False))

if __name__ == "__main__":
    ejecutar_ml_y_shap()